### ISSUE TITLE
🐛 [firebase_auth] WEB - on restart current user is NULL (emulator suite)

### ISSUE THREAD

**Issue by tomas-carv-com** [firebase/flutterfire#10200]
## Bug report

You can use https://github.com/firebase/flutterfire/blob/master/packages/firebase_auth/firebase_auth/example/lib/main.dart

latest firebase tools, flutter version, running in OSX & chrome with connected emulators.

When you run in and authenticate -> you are moved to profile page.

If you now reload page, current user is NULL and authChanges trigger will only render NULL value.

Even if you change persistence to Local / IndexDB.

**Comment by darshankawar** [comment]
Thanks for the report @tomas-carv-com 
I tried the example. Upon login and then on profile page, I hot restarted the app, it gave me the logged in user details properly as below:

```
User(displayName: Dantest test, email: dantesttest74@gmail.com, emailVerified: true, isAnonymous: false, metadata: UserMetadata(creationTime: 2022-01-07 11:09:02.000Z, lastSignInTime:
2023-01-02 11:43:02.000Z), phoneNumber: null, photoURL: https://lh3.googleusercontent.com/a/AATXAJxaO_5Y9F_fu4wXOaBjJJsDhdQAMQfTHvHDJZl4=s96-c, providerData, [UserInfo(displayName:
Dantest test, email: dantesttest74@gmail.com, phoneNumber: null, photoURL: https://lh3.googleusercontent.com/a/AATXAJxaO_5Y9F_fu4wXOaBjJJsDhdQAMQfTHvHDJZl4=s96-c, providerId: password,
uid: dantesttest74@gmail.com)],
```

**Comment by tomas-carv-com** [comment]
That does not seem as emulator output. Issue is with web & emulator suite

**Comment by darshankawar** [comment]
I am unable to replicate this using auth emulator.



> If you now reload page, current user is NULL and authChanges trigger will only render NULL value.

Can you provide relevant logs where it shows the current user as null upon hot restart ?

**Comment by Lyokone** [comment]
Can you also run `flutterfire update` to check if the Firebase packages are up to date?

**Comment by just7mile** [comment]
I'm having same issue with firebase_core v2.4.1 and firebase_auth v4.2.4. The problem is when using Firebase Emulator Suite in Flutter Web, it somehow tries to validate current user on `await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform)`, even before setting up emulators. So, it sends a POST request to `https://identitytoolkit.googleapis.com/v1/accounts:lookup?key=<key>` and gets 400 error response. 

Also, after this error all requests go to `identitytoolkit.googleapis.com` even though emulators are set, so it is impossible to login again. If initially no user is logged, then everything works fine, untill refreshing the page after signing in.

Code:
```dart
await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

await FirebaseAuth.instance.useAuthEmulator('localhost', 9099);
FirebaseFirestore.instance.useFirestoreEmulator('localhost', 8080);
```

Here is the developer tool log:

<img width="555" alt="image" src="https://user-images.githubusercontent.com/29413456/210575144-77f21d80-a927-41de-8c99-781ea6d0619c.png">

Could it be the issue is actually related with the native implementation of the firebase web (firebase.js)?

**Comment by arisAlexis** [comment]
exact same problem happening with emulator and web. On hot restart and with any persistence currentUser is null. When I set the persistence and inspect the instance object the field _persistence is null so being it's never set or something.

**Comment by Lyokone** [comment]
@just7mile We're going to see how to solve this. The linked commit was done to have a consistent behaviour between mobile and web, but definitely missed this issue.
We'll going to fix this ASAP

**Comment by cupidchan** [comment]
I experience the exact same issue and Andrei pointed me to this bug when he helped me to investigate other issues (Thanks Andrei!) 
@Lyokone, is there any update on this? The local development is blocked without this to be fixed. Thanks a lot!

**Comment by cupidchan** [comment]
Thanks for your update @Lyokone. We used Angular before switching to Flutter and the AngularFire counterpart works fine without issue. So, maybe we can adopt their approach in FlutterFire? 

@arisAlexis,  I set up `url` in the `ActionCodeSettings`. Then, i copy and past the link returned by Emulator in the browser and hope that it will redirect to `/#/profile` to discover this issue. I also set a break point in main and confirm that redirect back to the app will call main.

**Comment by Lyokone** [comment]
As a workaround, you can force this version of the `firebase_auth_web` in the pubspec.yaml:
```
firebase_auth_web: 5.1.3
```

**Comment by cupidchan** [comment]
@Lyokone unfortunately, I tried but it doesn't work...
```
Resolving dependencies...
Because firebase_auth 4.2.5 depends on firebase_auth_web ^5.2.4 and no versions of firebase_auth match >4.2.5 <5.0.0, firebase_auth ^4.2.5 requires firebase_auth_web ^5.2.4.
So, because flutter_application_1 depends on both firebase_auth ^4.2.5 and firebase_auth_web 5.1.3, version solving failed.
pub get failed
```

**Comment by purefundev** [comment]
@cupidchan try to downgrade the other ones too

The Git tag for that release is `firebase_auth_web-v5.1.3`:
 - firebase_core [is set to ^2.3.0](https://github.com/firebase/flutterfire/blob/firebase_auth_web-v5.1.3/packages/firebase_auth/firebase_auth_web/pubspec.yaml#L13) for example.
- firebase_auth [is a relative path](https://github.com/firebase/flutterfire/blob/firebase_auth_web-v5.1.3/packages/firebase_auth/firebase_auth_web/pubspec.yaml#L26) in there, it leads to [4.1.3](https://github.com/firebase/flutterfire/blob/firebase_auth_web-v5.1.3/packages/firebase_auth/firebase_auth/pubspec.yaml#L7) if we follow it

**Comment by purefundev** [comment]
@cupidchan are you able to downgrade those too? Might be a bad path to take if there has been a lot of development done on them in the meantime of course. I don't use them myself so don't have much insight into those side effects

This was their version no in the repo at the time when the desired version of firebase_auth_web was tagged for release, but maybe you wouldn't have to go that far:

https://github.com/firebase/flutterfire/blob/firebase_auth_web-v5.1.3/packages/firebase_ui_auth/pubspec.yaml#L3
https://github.com/firebase/flutterfire/blob/firebase_auth_web-v5.1.3/packages/firebase_ui_oauth_google/pubspec.yaml#L3
https://github.com/firebase/flutterfire/blob/firebase_auth_web-v5.1.3/packages/firebase_ui_oauth_apple/pubspec.yaml#L3

**Comment by cupidchan** [comment]
I agree with you @purefundev, downgrading them to a "workable" version is way too much to tweak and hence I keep "bugging" @Lyokone and see if there is any update from the Firebase team to truly resolve this issue, which has been opened for a month now.

**Comment by cupidchan** [comment]
@Lyokone any luck to get in touch with the Flutter team?

**Comment by Lyokone** [comment]
@cupidchan We still haven't got back from them. I'll create a small branch for you to use that will be in sync with master, so it's easier to use with current versions of other plugins

**Comment by afregeau** [comment]
Hi, any update on this?

I see the same as @cupidchan, because I am using firebase_ui_auth, which depends on the more recent (not yet fixed) firebase_auth, which also depends on (not yet fixed) firebase_auth_web.

Any tips would be appreciated, since firebase_ui_auth is a core part of our flow.

**Comment by cupidchan** [comment]
@Lyokone it's been a few weeks and the hot fix you put above relies on some conflicting dependencies. Can you please check what can make this fix sooner? Thanks!

**Comment by afregeau** [comment]
Actually, I am seeing something worse.

When I first launch the app, FirebaseAuth is correctly communicating with the emulator, but after a a refresh, FirebaseAuth is now pointing at the production auth server (!!)

Here is what I did:
1. Create two identical users in both production and the emulator. (I used "a@a.com", password: "test123" w/ email sign in)
2. Instruct the app to use the emulator in main()
```
  var initializeApp = await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  await FirebaseAuth.instance.useAuthEmulator('localhost', 9099);
```
3. Create a UI that:
a. Button to sign in the user above using the hardcoded credentials
c. Display the current user ID, or null.
5. Launch the app
6. Tap the button to log the user in

At this point, I correctly see the user ID from the **emulator** user.

Now, refresh the page, or hot reload the app.

1. The user shows as 'null'
2. Click the 'sign in' button again, with the same credentials
3. Observe that the User ID is the one from the _**production**_ auth platform. (!!!)


Refresh or hot reload again, you'll notice that the the User ID is now preserved (**_the production user Id_**) 


This is really scary, I hope someone can confirm what I am seeing, or otherwise point to a developer error. 


**_Note_** I am using `firebase_ui_auth: ^1.1.14`, which currently depends on
```
firebase_auth: ^4.2.9
firebase_core: ^2.7.0
```

**Comment by afregeau** [comment]
> @cupidchan We still haven't got back from them. I'll create a small branch for you to use that will be in sync with master, so it's easier to use with current versions of other plugins
> 
> You can use the hotfix version of firebase_auth_web here:
> 
> ```yaml
>   firebase_auth_web:
>     git:
>       url: https://github.com/firebase/flutterfire.git
>       ref: hotfix/web-user-null
>       path: packages/firebase_auth/firebase_auth_web
> ```

Additionally, this doesn't work for me. I get conflicting dependencies:
```
Resolving dependencies...
Because firebase_auth 4.2.9 depends on firebase_auth_web ^5.2.8 and no versions of firebase_auth match >4.2.9 <5.0.0, firebase_auth ^4.2.9 requires firebase_auth_web from hosted.
So, because *project* depends on both firebase_auth ^4.2.9 and firebase_auth_web from git, version solving failed.
```

If I put the hotfix into the override:
```
dependency_overrides:
  firebase_auth_web:
    git:
      url: https://github.com/firebase/flutterfire.git
      ref: hotfix/web-user-null
      path: packages/firebase_auth/firebase_auth_web
```

Then the app builds, but crashes on start.  `Error: MissingPluginException(No implementation found for method Auth#registerIdTokenListener on channel plugins.flutter.io/firebase_auth)`

**Comment by ahmednfwela** [comment]
@Lyokone this branch is out of sync with master, which doesn't have fixes for this issue https://github.com/firebase/flutterfire/issues/10478

**Comment by Lyokone** [comment]
I've updated the branch to be up to date with master. I have a meeting this week about this issue.

**Comment by cupidchan** [comment]
> I've updated the branch to be up to date with master. I have a meeting this week about this issue.

That's great @Lyokone This has been a long standing issue and should have a proper closure as soon as possible. Please keep us posted here!

**Comment by Lyokone** [comment]
Pushed the [fix here](https://github.com/firebase/flutterfire/pull/10565), you can try it early by using
```
  firebase_auth_web:
    git:
      url: https://github.com/firebase/flutterfire.git
      ref: fix/10200
      path: packages/firebase_auth/firebase_auth_web
```

**Comment by mzhang150** [comment]
I've been encountering the same issue and putting this fix into the dependency overrides seems to fix the error, as it no longer appears in the console, but some weird stuff still happens after verifying the user. The app is able to run and everything runs smoothly until the account is verified. A new user with no data is still created and is logged in. Errors no longer appear in the console though, which is odd, so I'm not entirely sure what's going on. 

(BTW, if the fix is placed under "dependencies:", the following issues arise similar to those in previous messages.) 
```
Resolving dependencies... Because no versions of firebase_auth match >4.2.5 <4.2.6 and firebase_auth >=4.2.6 <4.2.7 depends on firebase_auth_web ^5.2.5, firebase_auth >4.2.5 <4.2.7 requires firebase_auth_web ^5.2.5.
And because firebase_auth >=4.2.7 <4.2.8 depends on firebase_auth_web ^5.2.6 and firebase_auth >=4.2.8 <4.2.9 depends on firebase_auth_web ^5.2.7, firebase_auth >4.2.5 <4.2.9 requires firebase_auth_web ^5.2.5.
And because firebase_auth >=4.2.9 depends on firebase_auth_web ^5.2.8 and firebase_auth 4.2.5 depends on firebase_auth_web ^5.2.4, firebase_auth >=4.2.5 requires firebase_auth_web from hosted.
So, because flutter_application_1 depends on both firebase_auth ^4.2.5 and firebase_auth_web from git, version solving failed.
```

**Comment by cupidchan** [comment]
+1, @Lyokone, can you please check and see if there is any special setting is required to make this fix works? Thanks!

**Comment by Lyokone** [comment]
@mzhang150 I'm not sure about the bug you are describing. If it's not related to on restart the user being null, please open another issue.

@cupidchan You should add the dependency in the `dependency_overrides` section to make it work. You should not depend on the underlying package directly. It will probably be released today
