### ISSUE TITLE
🐛 [firebase_auth] FirebaseAuth.instance.currentUser initially null after initializing firebase on windows, even for logged in users

### ISSUE THREAD

**Issue by Justus-M** [firebase/flutterfire#12055]
## Bug report

**Describe the bug**

### Steps to reproduce

1. Login with FirebaseAuth on flutter windows
2. restart app and check FirebaseAuth.instance.currentUser immediately after initializing firebase
3. See that the value is null initially, and then changes after about 20 seconds

### Expected behavior

I expect the user to be shown on initialization, otherwise I have to add a delay (not sure how long it needs to be) or I don't know whether to show the login page or not.

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PS C:\Users\justinmulli\blazesql_flutter> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.16.4, on Microsoft Windows [Version 10.0.17763.5122], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.2)
[!] Android Studio (not installed)
[√] VS Code (version 1.85.1)
[√] Connected device (3 available)
[√] Network resources

! Doctor found issues in 2 categories.
PS C:\Users\justinmulli\blazesql_flutter>```


---

**Comment by danagbemava-nc** [comment]
Hi @Justus-M, is this limited to only windows or do you experience it on other platforms as well?

**Comment by Justus-M** [comment]
I haven't had time to create a minimum reproducible example but I imagine you can just use the example app and print FirebaseAuth.instance.currentUser immediately after initializing firebase.

I have added a delay of a few seconds and then it is no longer null, so to be honest this is no longer a priority for me. I believe it's an issue with the library so I wanted to bring it to your attention.

**Comment by Justus-M** [comment]
I provided more information

**Comment by danagbemava-nc** [comment]
Sorry for the delay, it seems like the bot didn't remove the blocked label so I missed it in my notifications. 

Reproducible using the plugin example app. I was already logged in, but the user came as null before the data was fully loaded.

cc @Lyokone 

```
Launching lib\main.dart on Windows in debug mode...
CMake Deprecation Warning at C:/Users/Deana/Desktop/example/firebase_auth_example/build/windows/x64/extracted/firebase_cpp_sdk_windows/CMakeLists.txt:17 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


√  Built build\windows\x64\runner\Debug\example.exe.
Connecting to VM Service at ws://127.0.0.1:50047/3U53madUGIc=/ws
flutter: user: null
flutter: user: null
[ERROR:flutter/shell/common/shell.cc(1015)] The 'firebase_auth_plugin/auth-state/[DEFAULT]' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel.
See https://docs.flutter.dev/platform-integration/platform-channels#channels-and-platform-threading for more information.
[ERROR:flutter/shell/common/shell.cc(1015)] The 'firebase_auth_plugin/id-token/[DEFAULT]' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel.
See https://docs.flutter.dev/platform-integration/platform-channels#channels-and-platform-threading for more information.
flutter: user: User(displayName: , email: payapp54@gmail.com, isEmailVerified: false, isAnonymous: false, metadata: UserMetadata(creationTime: null, lastSignInTime: null), phoneNumber: , photoURL: , providerData, [UserInfo(displayName: , email: payapp54@gmail.com, phoneNumber: , photoURL: , providerId: password, uid: payapp54@gmail.com)], refreshToken: null, tenantId: null, uid: AumEL2awh0NyOgfw1m7C8nGrsiK2)
[log] User(displayName: , email: payapp54@gmail.com, isEmailVerified: false, isAnonymous: false, metadata: UserMetadata(creationTime: null, lastSignInTime: null), phoneNumber: , photoURL: , providerData, [UserInfo(displayName: , email: payapp54@gmail.com, phoneNumber: , photoURL: , providerId: password, uid: payapp54@gmail.com)], refreshToken: null, tenantId: null, uid: AumEL2awh0NyOgfw1m7C8nGrsiK2)
```

**Comment by Lyokone** [comment]
Thanks for the report, I'm looking into it

**Comment by richard457** [comment]
This happen on other platform as well

**Comment by BirjuVachhani** [comment]
I am seeing this issue too on Windows. After I sign in/anonymous sign in, hot restarting the app returns currentUser as null. This also happens on subsequent app runs too.

**Comment by Hmida71** [comment]
someone solved the problem ?

**Comment by Hmida71** [comment]
> I am seeing this issue too on Windows. After I sign in/anonymous sign in, hot restarting the app returns currentUser as null. This also happens on subsequent app runs too.
> 
> In my case, it is always null, even after few seconds. I tried this:
> 
> ```
>  FirebaseAuth.instance.authStateChanges().listen((event) {
>       print('Auth state changed: $event');
>     });
> ```
> 
> and it only prints null and never prints again.

did you find solution ?

**Comment by BirjuVachhani** [comment]
I haven't. This makes our app useless on Windows! 🥲

**Comment by Hmida71** [comment]
> I haven't. This makes our app useless on Windows! 🥲

u can make delay its work but still bad !

**Comment by BirjuVachhani** [comment]
> > I haven't. This makes our app useless on Windows! 🥲
> 
> u can make delay its work but still bad !

I can't. Its not that it is only null for the first few seconds...it stays null. So it always logs out users when reopened.

**Comment by Hmida71** [comment]
> > > I haven't. This makes our app useless on Windows! 🥲
> > 
> > 
> > u can make delay its work but still bad !
> 
> I can't. Its not that it is only null for the first few seconds...it stays null. So it always logs out users when reopened.

try this : void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  FirebaseAuth.instance.authStateChanges().listen(
    (event) {
      if (event == null) {
        isLogin = false;
      } else {
        isLogin = true;
      }
    },
  );

  await Future.delayed((const Duration(seconds: 2))).then((value) {
    final user = FirebaseAuth.instance.currentUser;
    if (user == null) {
      isLogin = false;
    } else {
      isLogin = true;
    }
  });
  print(isLogin);
  runApp( .....

**Comment by remcova** [comment]
Are there any updates on this? I'm experiencing this too.

**Comment by Justus-M** [comment]
No updates as far as I'm aware, except that I lost several customers because of it

**Comment by remcova** [comment]
> No updates as far as I'm aware, except that I lost several customers because of it

Yeah same here. I'm trying to find a solution at the moment. I'll post it here once I find it.

**Comment by remcova** [comment]
@Justus-M do you use a YouTube scope by any chance for authentication?

**Comment by Justus-M** [comment]
No, I had users encountering this issue with a normal email and password
login

**Comment by remcova** [comment]
Okay. I think I found a solution. It's the way you handle authentication. My current implementation that works now, looks like this:
`    
await FirebaseAuth.instance.signInWithCredential(credential).whenComplete(() async { 
      final user = FirebaseAuth.instance.currentUser;
      // do something with user
});
`

Before I did it like this:
`
FirebaseAuth.instance.signInWithCredential(credential);
FirebaseAuth.instance.authStateChanges().listen((User? user) async {
// do something with the user object
}
`

I hope this solves the issue for you too!

**Comment by Justus-M** [comment]
I was never adding a listener in the first place, your issue probably
wasn’t network related like everyone else in this thread from the sounds of
it

**Comment by BirjuVachhani** [comment]
This issue makes Firebase useless because Windows app is un-usable. Can someone please look into this?

**Comment by remcova** [comment]
How do you handle the authentication then? I'm saying that I'm not experiencing this issue anymore.

**Comment by ronpetit** [comment]
I'm having this error too, seems related to the channel error as it looks relevant to the auth-state

[ERROR:flutter/shell/common/shell.cc(1015)] The 'firebase_auth_plugin/auth-state/[DEFAULT]' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel.
See https://docs.flutter.dev/platform-integration/platform-channels#channels-and-platform-threading for more information.

flutter 3.24.3
firebase_core 3.4.1
firebase_auth 5.2.1

**Comment by colonal** [comment]
I faced a similar issue where `FirebaseAuth.instance.currentUser` initially returned `null` for the first few seconds during Firebase initialization. Here's what I did to effectively handle this problem:

**Solution**

I utilized the `FirebaseAuth.instance.authStateChanges()` stream to listen for authentication state changes and created a `FirebaseAuthService` class to manage this behavior.


**FirebaseAuthService Class**
``` dart
class FirebaseAuthService{
    static bool isLoggedIn = false;
    
    static void authStateChanges() {
        FirebaseAuth.instance.authStateChanges().listen((event) {
          if (event != null) {
            isLoggedIn = true;
          } else {
            isLoggedIn = false;
          }
        });
    }
}
```

**Main File**

``` dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  FirebaseAuthService.authStateChanges();
  runApp(const FruitHub());
}
```

**Example: Checking Login Status in the Splash Screen**

From any file, you can check if the user is logged in. For example, in the splash screen:

``` Dart
var isLoggedIn = FirebaseAuthService.isLoggedIn;
if (isLoggedIn) {
  Navigator.pushReplacementNamed(context, MainView.routeName);
} else {
  Navigator.pushReplacementNamed(context, SignInView.routeName);
}
```

This approach ensures that your app correctly detects the user's authentication state as soon as it's available and navigates appropriately.

I hope this helps!

**Comment by BirjuVachhani** [comment]
@Lyokone Any updates on this?

**Comment by richard457** [comment]
I am afraid Google will kill this soon.

**Comment by SMDParsa** [comment]
Still having this bug issue on latest auth package 6.1.3, flutter 3.38.5, visual studio community 2026.

`[ERROR:flutter/shell/common/shell.cc(1015)] The 'firebase_auth_plugin/auth-state/[DEFAULT]' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel.
See https://docs.flutter.dev/platform-integration/platform-channels#channels-and-platform-threading for more information.`

Tried all solutions from from previous comments @colonal, @KKimj but still no luck.

I put print when auth completed it shows before this error.

**Comment by BirjuVachhani** [comment]
Seems like this will never get fixed!

**Comment by richard457** [comment]
Yes

**Comment by jeffbui152** [comment]
13/01/2026 i stil get this error
Flutter version 3.38.x

**Comment by venky9885** [comment]
@Lyokone  Any update on this

**Comment by mubiru-simeon** [comment]
Same issue here. I get a null on trying to get current user, even when user is clearly signed in. Flutter desktop. Windows. firebase auth firebase_auth: ^6.1.2
