### ISSUE TITLE
🐛 [firebase_core] TypeError: Class constructor IndexedDBLocalPersistence cannot be invoked without 'new'

### ISSUE THREAD

**Issue by a-wallen** [firebase/flutterfire#12291]
## Bug report

**Describe the bug**
Flutter web project on `master` shows a white screen on startup. Here's the logs:

```
TypeError: Class constructor IndexedDBLocalPersistence cannot be invoked without 'new'
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 462:37   _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 555:39   dcall
https://www.gstatic.com/firebasejs/10.3.1/firebase-auth.js 1:47688                 _getInstance
https://www.gstatic.com/firebasejs/10.3.1/firebase-auth.js 1:144541                _initializeAuthInstance
https://www.gstatic.com/firebasejs/10.3.1/firebase-auth.js 1:144689                instanceFactory
https://www.gstatic.com/firebasejs/10.3.1/firebase-app.js 977:39                   getOrInitializeService
https://www.gstatic.com/firebasejs/10.3.1/firebase-app.js 921:31                   initialize
https://www.gstatic.com/firebasejs/10.3.1/firebase-auth.js 1:67079                 initializeAuth
packages/firebase_auth_web/src/interop/auth.dart 24:40                             getAuthInstance
packages/firebase_auth_web/firebase_auth_web.dart 91:43                            <fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                 runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 127:5                 _async
packages/firebase_auth_web/firebase_auth_web.dart 90:33                            <fn>
packages/firebase_core_web/src/firebase_core_web.dart 310:41                       <fn>
dart-sdk/lib/internal/iterable.dart 403:20                                         moveNext
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 1139:20  next
dart-sdk/lib/async/future.dart 516:16                                              wait
packages/firebase_core_web/src/firebase_core_web.dart 302:18                       initializeApp
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50                 <fn>
dart-sdk/lib/async/zone.dart 1661:54                                               runUnary
dart-sdk/lib/async/future_impl.dart 162:18                                         handleValue
dart-sdk/lib/async/future_impl.dart 838:44                                         handleValueCallback
dart-sdk/lib/async/future_impl.dart 867:13                                         _propagateToListeners
dart-sdk/lib/async/future_impl.dart 643:5                                          [_completeWithValue]
dart-sdk/lib/async/future.dart 524:22                                              <fn>
dart-sdk/lib/async/zone.dart 1661:54                                               runUnary
dart-sdk/lib/async/future_impl.dart 162:18                                         handleValue
dart-sdk/lib/async/future_impl.dart 838:44                                         handleValueCallback
dart-sdk/lib/async/future_impl.dart 867:13                                         _propagateToListeners
dart-sdk/lib/async/future_impl.dart 643:5                                          [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 713:7                                          callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                                   _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                                    _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7                 <fn>
```

looks like other people on [Stack Overflow](https://stackoverflow.com/questions/77705647/flutter-typeerror-class-constructor-indexeddblocalpersistence-cannot-be-invok) and [Reddit](https://www.reddit.com/r/flutterhelp/comments/1934e88/is_anyone_else_having_issues_with_flutter_web/) are having the same issue.

### Steps to reproduce

I'm on the `master` channel and I imported a couple firebase packages into my flutter web project.

### Expected behavior

The app runs normally

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.19.0-9.0.pre.90, on Microsoft Windows [Version 10.0.19045.3930], locale en-US)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.0)
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.86.0)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 3.4.0-60.0.dev
Flutter SDK 3.19.0-9.0.pre.90
builder 1.0.0+1

dependencies:
- analytics_repository 0.0.0 [equatable firebase_analytics flutter very_good_analysis]
- animations 2.0.11 [flutter]
- core 0.0.1 [awesome_bottom_bar awesome_drawer_bar equatable flutter flutter_advanced_drawer flutter_fancy_tree_view flutter_inappwebview flutter_zoom_drawer freezed_annotation icon_forest json_annotation uuid]
- deep_link_client 0.0.0 [equatable firebase_core firebase_dynamic_links plugin_platform_interface rxdart very_good_analysis]
- device_preview 1.1.0 [flutter flutter_localizations provider device_frame freezed_annotation json_annotation shared_preferences collection]
- dotted_border 2.1.0 [flutter path_drawing]
- dummy_subscription_client 1.0.0 [subscription_client]
- firebase_analytics 10.5.1 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_authentication_client 1.0.0+1 [authentication_client firebase_auth firebase_auth_platform_interface firebase_core firebase_core_platform_interface flutter flutter_facebook_auth google_sign_in plugin_platform_interface sign_in_with_apple token_storage twitter_login]
- firebase_core 2.17.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 3.3.7 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_dynamic_links 5.3.7 [firebase_core firebase_core_platform_interface firebase_dynamic_links_platform_interface flutter meta plugin_platform_interface]
- flex_color_picker 3.3.1 [flex_seed_scheme flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_advanced_drawer 1.3.5 [flutter]
- flutter_bloc 8.1.3 [bloc flutter provider]
- flutter_fancy_tree_view 1.4.1 [flutter]
- flutter_zoom_drawer 3.1.1 [flutter]
- freezed 2.4.6 [analyzer build build_config collection meta source_gen freezed_annotation json_annotation]
- freezed_annotation 2.4.1 [collection json_annotation meta]
- google_fonts 6.1.0 [flutter http path_provider crypto]
- image_cropper 5.0.1 [flutter image_cropper_platform_interface image_cropper_for_web]
- image_picker 1.0.7 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_linux image_picker_macos image_picker_platform_interface image_picker_windows]
- json_annotation 4.8.1 [meta]
- package_info_client 1.0.0+1 [equatable]
- persistent_storage 0.0.0 [flutter shared_preferences storage]
- shared_preferences 2.2.2 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- smooth_page_indicator 1.1.0 [flutter]
- string_similarity 2.0.0
- surge_adaptive_layouts 0.0.1 [flutter]
- token_storage 1.0.0+1
- user_repository 0.0.0 [authentication_client deep_link_client equatable package_info_client rxdart storage subscription_client]
- uuid 4.3.3 [crypto sprintf meta fixnum]

dev dependencies:
- build_runner 2.4.8 [analyzer args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_lints 2.0.3 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]
- json_serializable 6.7.1 [analyzer async build build_config collection json_annotation meta path pub_semver pubspec_parse source_gen source_helper]

dependency overrides:
- http 1.2.0 [async http_parser meta web]

transitive dependencies:
- _fe_analyzer_shared 66.0.0 [meta]
- _flutterfire_internals 1.3.7 [collection firebase_core firebase_core_platform_interface flutter meta]
- analyzer 6.4.0 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- args 2.4.2
- async 2.11.0 [collection meta]
- authentication_client 0.0.0 [equatable]
- awesome_bottom_bar 1.2.4 [flutter]
- awesome_drawer_bar 1.2.0 [flutter flutter_adaptive_scaffold]
- bloc 8.1.2 [meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- build 2.4.1 [analyzer async convert crypto glob logging meta package_config path]
- build_config 1.1.1 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 4.0.1 [built_collection built_value crypto http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]        
- build_resolvers 2.4.2 [analyzer async build collection convert crypto graphs logging package_config path pool pub_semver stream_transform yaml]
- build_runner_core 7.2.11 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta package_config path pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.8.1 [built_collection collection fixnum meta]
- characters 1.3.0
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- clock 1.1.1
- code_builder 4.10.0 [built_collection built_value collection matcher meta]
- collection 1.18.0
- convert 3.1.1 [typed_data]
- cross_file 0.3.3+8 [meta web]
- crypto 3.0.3 [typed_data]
- cupertino_icons 1.0.6
- dart_style 2.3.4 [analyzer args collection path pub_semver source_span]
- device_frame 1.1.0 [freezed_annotation flutter]
- equatable 2.0.5 [collection meta]
- facebook_auth_desktop 0.0.9 [flutter http flutter_secure_storage flutter_facebook_auth_platform_interface]
- fake_async 1.3.1 [clock collection]
- ffi 2.1.2
- file 7.0.0 [meta path]
- file_selector_linux 0.9.2+1 [cross_file file_selector_platform_interface flutter]
- file_selector_macos 0.9.3+3 [cross_file file_selector_platform_interface flutter]
- file_selector_platform_interface 2.6.2 [cross_file flutter http plugin_platform_interface]
- file_selector_windows 0.9.3+1 [cross_file file_selector_platform_interface flutter]
- firebase_analytics_platform_interface 3.7.1 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.5+1 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_auth 4.10.1 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_auth_platform_interface 6.19.1 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.8.2 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser js meta]
- firebase_core_platform_interface 4.8.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.8.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.6.7 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_dynamic_links_platform_interface 0.2.6+7 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- fixnum 1.1.0
- flex_seed_scheme 1.4.0 [collection flutter meta]
- flutter_adaptive_scaffold 0.0.9 [flutter]
- flutter_facebook_auth 5.0.11 [flutter flutter_facebook_auth_platform_interface flutter_facebook_auth_web facebook_auth_desktop]
- flutter_facebook_auth_platform_interface 4.1.1 [flutter plugin_platform_interface]
- flutter_facebook_auth_web 4.1.1 [flutter flutter_web_plugins js flutter_facebook_auth_platform_interface]
- flutter_inappwebview 6.0.0 [flutter flutter_inappwebview_platform_interface flutter_inappwebview_android flutter_inappwebview_ios flutter_inappwebview_macos flutter_inappwebview_web]
- flutter_inappwebview_android 1.0.12 [flutter flutter_inappwebview_platform_interface]
- flutter_inappwebview_internal_annotations 1.1.1
- flutter_inappwebview_ios 1.0.13 [flutter flutter_inappwebview_platform_interface]
- flutter_inappwebview_macos 1.0.11 [flutter flutter_inappwebview_platform_interface]
- flutter_inappwebview_platform_interface 1.0.10 [flutter flutter_inappwebview_internal_annotations plugin_platform_interface]
- flutter_inappwebview_web 1.0.8 [flutter flutter_web_plugins js flutter_inappwebview_platform_interface]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_plugin_android_lifecycle 2.0.17 [flutter]
- flutter_secure_storage 8.1.0 [flutter flutter_secure_storage_linux flutter_secure_storage_macos flutter_secure_storage_platform_interface flutter_secure_storage_web flutter_secure_storage_windows meta]
- flutter_secure_storage_linux 1.2.0 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_macos 3.0.1 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_platform_interface 1.0.2 [flutter plugin_platform_interface]
- flutter_secure_storage_web 1.1.2 [flutter flutter_secure_storage_platform_interface flutter_web_plugins js]
- flutter_secure_storage_windows 2.1.1 [flutter flutter_secure_storage_platform_interface]
- flutter_svg 1.1.6 [flutter meta path_drawing vector_math xml]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- frontend_server_client 3.2.0 [async path]
- glob 2.1.2 [async collection file path string_scanner]
- google_identity_services_web 0.3.0+2 [meta web]
- google_sign_in 6.2.1 [flutter google_sign_in_android google_sign_in_ios google_sign_in_platform_interface google_sign_in_web]
- google_sign_in_android 6.1.21 [flutter google_sign_in_platform_interface]
- google_sign_in_ios 5.7.3 [flutter google_sign_in_platform_interface]
- google_sign_in_platform_interface 2.4.5 [flutter plugin_platform_interface]
- google_sign_in_web 0.12.3+2 [flutter flutter_web_plugins google_identity_services_web google_sign_in_platform_interface http web]
- graphs 2.3.1 [collection]
- http_multi_server 3.2.1 [async]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- icon_forest 1.1.8 [flutter cupertino_icons flutter_svg path url_launcher]
- image_cropper_for_web 3.0.0 [flutter flutter_web_plugins image_cropper_platform_interface js]
- image_cropper_platform_interface 5.0.0 [flutter plugin_platform_interface http]
- image_picker_android 0.8.9+3 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 3.0.2 [flutter flutter_web_plugins image_picker_platform_interface mime]
- image_picker_ios 0.8.9+1 [flutter image_picker_platform_interface]
- image_picker_linux 0.2.1+1 [file_selector_linux file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_macos 0.2.1+1 [file_selector_macos file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_platform_interface 2.9.3 [cross_file flutter http plugin_platform_interface]
- image_picker_windows 0.2.1+1 [file_selector_platform_interface file_selector_windows flutter image_picker_platform_interface]
- intl 0.18.1 [clock meta path]
- io 1.0.4 [meta path string_scanner]
- js 0.6.5 [meta]
- leak_tracker 10.0.1 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 2.0.3 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 2.0.2 [leak_tracker matcher meta]
- lints 2.0.1
- logging 1.2.0
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.8.0 [collection]
- meta 1.11.0
- mime 1.0.4
- nested 1.0.0 [flutter]
- package_config 2.1.0 [path]
- path 1.9.0
- path_drawing 1.0.1 [vector_math meta path_parsing flutter]
- path_parsing 1.0.1 [vector_math meta]
- path_provider 2.1.2 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- path_provider_android 2.2.2 [flutter path_provider_platform_interface]
- path_provider_foundation 2.3.2 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- path_provider_windows 2.2.1 [ffi flutter path path_provider_platform_interface win32]
- petitparser 6.0.2 [meta]
- platform 3.1.4
- plugin_platform_interface 2.1.8 [meta]
- pool 1.5.1 [async stack_trace]
- provider 6.1.1 [collection flutter nested]
- pub_semver 2.1.4 [collection meta]
- pubspec_parse 1.2.3 [checked_yaml collection json_annotation pub_semver yaml]
- rxdart 0.27.7
- shared_preferences_android 2.2.1 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.3.5 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.3.2 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.3.2 [flutter plugin_platform_interface]
- shared_preferences_web 2.2.2 [flutter flutter_web_plugins shared_preferences_platform_interface web]
- shared_preferences_windows 2.3.2 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.4.1 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 1.0.4 [shelf stream_channel web_socket_channel]
- sign_in_with_apple 4.3.0 [flutter meta sign_in_with_apple_platform_interface sign_in_with_apple_web]
- sign_in_with_apple_platform_interface 1.0.0 [flutter plugin_platform_interface meta]
- sign_in_with_apple_web 1.0.1 [flutter flutter_web_plugins sign_in_with_apple_platform_interface js]
- sky_engine 0.0.99
- source_gen 1.5.0 [analyzer async build dart_style glob path source_span yaml]
- source_helper 1.3.4 [analyzer collection source_gen]
- source_span 1.10.0 [collection path term_glyph]
- sprintf 7.0.0
- stack_trace 1.11.1 [path]
- storage 0.0.0
- stream_channel 2.1.2 [async]
- stream_transform 2.1.0
- string_scanner 1.2.0 [source_span]
- subscription_client 1.0.0 [equatable json_annotation]
- term_glyph 1.2.1
- test_api 0.6.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- timing 1.0.1 [json_annotation]
- twitter_login 4.4.2 [crypto flutter http]
- typed_data 1.3.2 [collection]
- url_launcher 6.2.4 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- url_launcher_android 6.2.2 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.2.4 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.1.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.1.0 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.3.1 [flutter plugin_platform_interface]
- url_launcher_web 2.2.3 [flutter flutter_web_plugins url_launcher_platform_interface web]
- url_launcher_windows 3.1.1 [flutter url_launcher_platform_interface]
- vector_math 2.1.4
- very_good_analysis 4.0.0+1
- vm_service 13.0.0
- watcher 1.1.0 [async path]
- web 0.4.2
- web_socket_channel 2.4.3 [async crypto stream_channel web]
- win32 5.2.0 [ffi]
- xdg_directories 1.0.4 [meta path]
- xml 6.5.0 [collection meta petitparser]
- yaml 3.1.2 [collection source_span string_scanner]
```

</details>

---

**Comment by woutervanwijk** [comment]
I can confirm :(

**Comment by Lyokone** [comment]
Thanks for the report, on Flutter stable we resolve to web 0.3.0, when on beta/master you resolve to web 0.4.2 that seems to cause an issue. Let me look into it

**Comment by delizondo** [comment]
I've just updated to Flutter 3.19.0, getting this error as well, I've already updated all the firebase packages to the latest version, `flutter clean`  and no change.


```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.0, on macOS 14.3.1 23D60 darwin-arm64,
    locale en-CR)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.86.2)
```

**Comment by wrpeck** [comment]
@delizondo - worked for me too, thank you! Saved me a couple hours of troubleshooting

**Comment by johnyp** [comment]
Ive tried downgrading and tons of different approaches, i cant my project to run properly on web, causing me alot of issues.. What version of firebase_auth and firebase_core are you guys using? What is the root of the problem i cant get my project to work.

**Comment by sma** [comment]
You need a flutter version that uses `web 0.3.0` because FlutterFire is compatible with both `web 0.4.x` and `web 0.5.0` (he current version at the moment).

**Comment by johnyp** [comment]
This is the version im using atm, i downgraded, but i get the error that my firebase exceptions now is returning unknown, making the code not running properly, its not entering the correct catch clause.. does anyone encounter the same issue as me?

[firebase_auth/unknown] An unknown error occurred: FirebaseError: Firebase: Proof of ownership of a second factor is required to complete sign-in. (auth/multi-factor-auth-required).

• Flutter version 3.16.9 on channel stable at C:\Flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41456452f2 (3 weeks ago), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5

**Comment by johnyp** [comment]
Just want to add that everything worked before i updated to 3.19 version, now even thou i downgrade i get the firebase "unknown" issue which ive never encountered before.

**Comment by kane-knowby** [comment]
This is now broken on stable with the release of 3.19.0, far as I can tell. Any work arounds besides downgrading to 3.16.X?

**Comment by EricPHassey** [comment]
> This is now broken on stable with the release of 3.19.0, far as I can tell. Any work arounds besides downgrading to 3.16.X?

Same with me. The new update broke it. Looking for a fix. Downgrading firebase_core to 2.24.2 didn't seem to resolve it either.

**Comment by beefchalupa** [comment]
Latest update to 3.19 broke mine as well. Getting the exact same error, can no longer launch my app in web

**Comment by Fevzettin1** [comment]
It broke for me too after the update (I get the same error on the web) and downgrading didn't work.

**Comment by johnyp** [comment]
For the people who got it working on version 3.16.9 could you please share your exact versions of firebase_auth and firebase_core, the version can be found in the pubspec.lock file..

**Comment by beefchalupa** [comment]
> For the people who got it working on version 3.16.9 could you please share your exact versions of firebase_auth and firebase_core, the version can be found in the pubspec.lock file..

My firebause_auth is 4.17.4 and firebase_core is 2.25.4 in pubspec.lock

In pubspec.yaml I have auth at ^4.17.0 and core at ^2.25.3

**Comment by johnyp** [comment]
> > For the people who got it working on version 3.16.9 could you please share your exact versions of firebase_auth and firebase_core, the version can be found in the pubspec.lock file..
> 
> My firebause_auth is 4.17.4 and firebase_core is 2.25.4 in pubspec.lock
> 
> In pubspec.yaml I have auth at ^4.17.0 and core at ^2.25.3

Thanks, what is your version on: firebase_app_check?

**Comment by beefchalupa** [comment]
> > > For the people who got it working on version 3.16.9 could you please share your exact versions of firebase_auth and firebase_core, the version can be found in the pubspec.lock file..
> > 
> > 
> > My firebause_auth is 4.17.4 and firebase_core is 2.25.4 in pubspec.lock
> > In pubspec.yaml I have auth at ^4.17.0 and core at ^2.25.3
> 
> Thanks, what is your version on: firebase_app_check?

I'm not using app check at all right now

**Comment by johnyp** [comment]
> ^2.25.3



> > > > For the people who got it working on version 3.16.9 could you please share your exact versions of firebase_auth and firebase_core, the version can be found in the pubspec.lock file..
> > > 
> > > 
> > > My firebause_auth is 4.17.4 and firebase_core is 2.25.4 in pubspec.lock
> > > In pubspec.yaml I have auth at ^4.17.0 and core at ^2.25.3
> > 
> > 
> > Thanks, what is your version on: firebase_app_check?
> 
> I'm not using app check at all right now

Okey, and are you using MFA for authentication? Problem im getting is that the authentication response is not responding the same codes as it normally has done, making my code just entering the catch clause which handles incorrect email and password, while it should be landing on the FirebaseAuthMultiFactorException catch clause.

**Comment by johnyp** [comment]
My app is running on web but the issue im getting is:

`[firebase_auth/unknown] An unknown error occurred: FirebaseError: Firebase: Proof of ownership of a second factor is required to complete sign-in. (auth/multi-factor-auth-required).`

So my code never enters this caluse:
` } on FirebaseAuthMultiFactorException catch (e) {`

And its there i have the logic to handle the MFA, it goes straight to this clause:
`    } on FirebaseAuthMultiFactorException catch (e) {`
Where e.code === "unknown"

**Comment by russellwheatley** [comment]
> My app is running on web but the issue im getting is:
> 
> `[firebase_auth/unknown] An unknown error occurred: FirebaseError: Firebase: Proof of ownership of a second factor is required to complete sign-in. (auth/multi-factor-auth-required).`
> 
> So my code never enters this caluse: ` } on FirebaseAuthMultiFactorException catch (e) {`
> 
> And its there i have the logic to handle the MFA, it goes straight to this clause: ` } on FirebaseAuthMultiFactorException catch (e) {` Where e.code === "unknown"
> 
> Is anyone using MFA and got it working?
 
@johnyp - We have a fix for this in the next release which will be out on Monday.

**Comment by johnyp** [comment]
> > My app is running on web but the issue im getting is:
> > `[firebase_auth/unknown] An unknown error occurred: FirebaseError: Firebase: Proof of ownership of a second factor is required to complete sign-in. (auth/multi-factor-auth-required).`
> > So my code never enters this caluse: ` } on FirebaseAuthMultiFactorException catch (e) {`
> > And its there i have the logic to handle the MFA, it goes straight to this clause: ` } on FirebaseAuthMultiFactorException catch (e) {` Where e.code === "unknown"
> > Is anyone using MFA and got it working?
> 
> @johnyp - We have a fix for this in the next release which will be out on Monday.

Alright, i just got it working by reverting my firebase dependencies, so using firebase_auth: 4.10.0 and firebase_core: 2.17.0 and firebase_app_check: ^0.2.0 works. Probably other versions works aswell but i just had to get my app running because i had a feature i had to release.. I reverted also to Flutter 3.16.5 but i bet that version 3.16.9 works aswell.

**Comment by russellwheatley** [comment]
I am trying to resolve this issue:
```
Class constructor BrowserPopupRedirectResolver cannot be invoked without 'new'
```

It appears there is a difference in how the latest Flutter SDK handles classes: https://github.com/firebase/flutterfire/blob/master/packages/firebase_auth/firebase_auth_web/lib/src/interop/auth_interop.dart#L36

We pass it in here: https://github.com/firebase/flutterfire/blob/master/packages/firebase_auth/firebase_auth_web/lib/src/interop/auth.dart#L31

It seems it is trying to invoke it. In JS, it is a class. The firebase auth web JS SDK initializeAuth() function expects it as an argument without invoking it (i.e. the class object).

**Comment by giaesp** [comment]
Something went wrong with Firebase Auth persistence, so I tried to disable it using the following code:

`if (kDebugMode) await FirebaseAuth.instance.setPersistence(Persistence.NONE);`

Now I'm getting a different error:

Error: TypeError: Instance of 'FirebaseException': type 'FirebaseException' is not a subtype of type 'JavaScriptObject'
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 297:3  throw_
dart-sdk/lib/_internal/js_shared/lib/rti.dart 1385:3                         _failedAsCheck
dart-sdk/lib/_internal/js_shared/lib/rti.dart 1363:3                         _generalAsCheckImplementation
packages/firebase_core_web/src/firebase_core_web.dart 336:29                 app
packages/firebase_core/src/firebase.dart 56:41                               app
packages/firebase_auth/src/firebase_auth.dart 38:47                          get instance
packages/graph_editor/main.dart 14:47                                        main

**Comment by amrgetment** [comment]
@russellwheatley could we get a fix on master so we can just use master branch until you publish on Monday

**Comment by russellwheatley** [comment]
> Something went wrong with Firebase Auth persistence, so I tried to disable it using the following code:
> 
> `if (kDebugMode) await FirebaseAuth.instance.setPersistence(Persistence.NONE);`
> 
> Now I'm getting a different error:
> 
> Error: TypeError: Instance of 'FirebaseException': type 'FirebaseException' is not a subtype of type 'JavaScriptObject' dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 297:3 throw_ dart-sdk/lib/_internal/js_shared/lib/rti.dart 1385:3 _failedAsCheck dart-sdk/lib/_internal/js_shared/lib/rti.dart 1363:3 _generalAsCheckImplementation packages/firebase_core_web/src/firebase_core_web.dart 336:29 app packages/firebase_core/src/firebase.dart 56:41 app packages/firebase_auth/src/firebase_auth.dart 38:47 get instance packages/graph_editor/main.dart 14:47 main

@giaesp - Pretty sure this is fixed as a result of this PR:https://github.com/firebase/flutterfire/pull/12319

**Comment by russellwheatley** [comment]
> @russellwheatley could we get a fix on master so we can just use master branch until you publish on Monday

@amrgetment - working on it: https://github.com/firebase/flutterfire/pull/12338. 

CI has gone green for auth web. It seems the latest Flutter release has also broken our CI tooling installation so figuring that out at the moment 👍

**Comment by amrgetment** [comment]
@russellwheatley thanks

here is my use for Russell fix and it works for me


```
dependency_overrides:
  web: ^0.4.2
  firebase_auth_web:
    git:
      url: git@github.com:firebase/flutterfire.git
      ref: web-ci
      path: packages/firebase_auth/firebase_auth_web

```

**Comment by russellwheatley** [comment]
It has now been merged into master branch and the latest release will go out on Monday 👍

**Comment by Mmisiek** [comment]
I switch to master but still get this error when opening the debug connection to firebase. The production is OK.

**Comment by nathanblair** [comment]
How might I switch to a `master` version of the `firebase_auth_web` package to verify this should be working?

**Comment by IchordeDionysos** [comment]
@nathanblair https://github.com/firebase/flutterfire/issues/12291#issuecomment-1948455179

**Comment by omegaui** [comment]
@russellwheatley 
Hi! Is the release out?

**Comment by omegaui** [comment]
I'm still gettings the same error even after pub upgrade (it didn't changed any firebase dependency though).
Using Flutter `3.19.0`.
I have been waiting since Saturday to work on my project.
Also, [comment](https://github.com/firebase/flutterfire/issues/12291#issuecomment-1948455179) is not working for me.

**Comment by isrgold** [comment]
> I'm still gettings the same error even after pub upgrade (it didn't changed any firebase dependency though). Using Flutter `3.19.0`. I have been waiting since Saturday to work on my project. Also, [comment](https://github.com/firebase/flutterfire/issues/12291#issuecomment-1948455179) is not working for me.

you can downgrade back to 3.16.9 in the meantime to work on your project

**Comment by omegaui** [comment]
@isrgold 
Thanks for mentioning but I tried it earlier
```sh
Resolving dependencies...
Git error. Command: `git clone --mirror git@github.com:firebase/flutterfire.git /home/omegaui/.pub-cache/git/cache/flutterfire-c45e989a6f8e3ced351e99dcf2815badfae533e2`
stdout: 
stderr: Cloning into bare repository '/home/omegaui/.pub-cache/git/cache/flutterfire-c45e989a6f8e3ced351e99dcf2815badfae533e2'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
exit code: 128
````

I'm getting the above error while using dependecy_overrides.

**Comment by omegaui** [comment]
on Flutter 3.16.5

**Comment by omegaui** [comment]
@russellwheatley Thank you for fixing this issue 😇

**Comment by johnyp** [comment]
@russellwheatley Is this now fixed? I saw that some tests for web had failed.

**Comment by russellwheatley** [comment]
@johnyp - It is fixed and released 👍

**Comment by Fevzettin1** [comment]
> @johnyp - It is fixed and released 👍

i have the same problem, on Flutter 3.20.0-10.0.pre.43 • channel master.
(error: TypeError: Class constructor IndexedDBLocalPersistence cannot be invoked without 'new')

and pubspec.yaml vers:
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  firebase_storage: ^11.6.6
  cloud_firestore: ^4.15.5

**Comment by johnyp** [comment]
> @johnyp - It is fixed and released 👍

Thanks! Seems to be working fine now

**Comment by woutervanwijk** [comment]
Great, it works! I can build it with
 firebase_crashlytics: ^3.4.14
but 
 firebase_crashlytics: ^3.4.15 
gives errors

**Comment by russellwheatley** [comment]
@woutervanwijk - please create a new issue if you have found a bug. Thanks.

**Comment by devloic** [comment]
> dependency_overrides:
>   web: ^0.4.2
>   firebase_auth_web:
>     git:
>       url: git@github.com:firebase/flutterfire.git
>       ref: master
>       path: packages/firebase_auth/firebase_auth_web


> @isrgold Thanks for mentioning but I tried it earlier
> 
> ```shell
> Resolving dependencies...
> Git error. Command: `git clone --mirror git@github.com:firebase/flutterfire.git /home/omegaui/.pub-cache/git/cache/flutterfire-c45e989a6f8e3ced351e99dcf2815badfae533e2`
> stdout: 
> stderr: Cloning into bare repository '/home/omegaui/.pub-cache/git/cache/flutterfire-c45e989a6f8e3ced351e99dcf2815badfae533e2'...
> git@github.com: Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> exit code: 128
> ```
> 
> I'm getting the above error while using dependecy_overrides.


create a new ssh key following :
https://docs.github.com/en/authentication/troubleshooting-ssh/error-permission-denied-publickey

**Comment by Mmisiek** [comment]
> @johnyp - It is fixed and released 👍

Which version and channel? I switched back to `stable` and the issue is still there.

**Comment by isaacadariku** [comment]
I am not sure this is released yet to `stable`.  In case you got this error 
```
Launching lib/main_web.dart on Chrome in debug mode...
../../../.pub-cache/git/flutterfire-f24d0a76ff384cf40605ae59af705b2854e53ba7/packages/firebase_auth/firebase_auth_web/lib/src/interop/auth.dart:36:22: Error: Method not found: 'customJSList'.
        persistence: customJSList(persistences),
                     ^^^^^^^^^^^^
```
You can fix it by updating @amrgetment comment https://github.com/firebase/flutterfire/issues/12291#issuecomment-1948455179 with the commit sha. 

```yaml
dependency_overrides:
  web: ^0.4.2
  firebase_auth_web:
    git:
      url: git@github.com:firebase/flutterfire.git
      ref: 9d5480f8f943d095dd3ca94d4868ec75bed84b22
      path: packages/firebase_auth/firebase_auth_web
```

While we wait for the stable release, this will fix that issue.

**Comment by Oskar888** [comment]
i have error still on master channel

**Comment by v2thegreat** [comment]
Getting the same error as well. What's going on?

**Comment by russellwheatley** [comment]
Try `flutter pub upgrade`. This has been fixed. Adding comments with no context does not help. Please create a new issue with reproduction if you think you have found another bug as asked here:

> @woutervanwijk - please create a new issue if you have found a bug. Thanks.
