### ISSUE TITLE
[cloud_firestore]: iOS Firebase 11.0.0 - CocoaPods could not find compatible versions for pod "nanopb"

### ISSUE THREAD

**Issue by jt274** [firebase/flutterfire#13228]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Crashlytics, Other

### Which platforms are affected?

iOS

### Description

After upgrading to `cloud_firestore` `5.3.0` and `firebase_crashlytics` `4.1.0` and building an app for iOS, the following error is given:

```
[!] CocoaPods could not find compatible versions for pod "nanopb":
      In Podfile:
        FirebaseFirestore (from `[https://github.com/invertase/firestore-ios-sdk-frameworks.git`](https://github.com/invertase/firestore-ios-sdk-frameworks.git), tag `11.0.0`) was resolved to 11.0.0, which depends on
          FirebaseFirestoreBinary (= 11.0.0) was resolved to 11.0.0, which depends on
            FirebaseFirestoreInternalBinary (= 11.0.0) was resolved to 11.0.0, which depends on
              nanopb (< 2.30911.0, >= 2.30908.0)

        firebase_crashlytics (from `.symlinks/plugins/firebase_crashlytics/ios`) was resolved to 4.1.0, which depends on
          Firebase/Crashlytics (= 11.0.0) was resolved to 11.0.0, which depends on
            FirebaseCrashlytics (~> 11.0.0) was resolved to 11.0.0, which depends on
              nanopb (~> 3.30910.0)
```

I have:

- Deleted `Pods` folder
- Deleted `.symlinks` folder
- Deleted `Podfile.lock`
- Run `flutter clean`
- Run `flutter pub cache clean`
- Run `flutter pub get`
- Run `pod repo update`
- Run `pod update`

And still receive the above error.

Related to https://github.com/invertase/firestore-ios-sdk-frameworks/issues/108

### Reproducing the issue

1. Upgrade to latest flutterfire packages (including `cloud_firestore` `5.3.0` and `firebase_crashlytics` `4.1.0`)
2. Run pod install for iOS

### Firebase Core version

3.4.0

### Flutter Version

3.24.1

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by yuukiw00w** [comment]
In flutterfire, the definition that references the old nanopb has been deleted in the following commit:
https://github.com/firebase/flutterfire/commit/c899a7bc9cdd7b552d3c10058f4899106a4c1994

In firestore-ios-sdk-frameworks, there are still definitions that refer to the old nanopb
https://github.com/invertase/firestore-ios-sdk-frameworks/blob/c1fc6ae59c96b43a900e7a4c77a6c74929d7990f/FirebaseFirestore.podspec#L9

**Comment by jmgeffroy** [comment]
Same issue there. The strange thing is that I reverted back to `firebase_crashlytics 4.0.4` and `cloud_firestore 5.2.1` (without `^`), and I still have the issue:

```
    [!] CocoaPods could not find compatible versions for pod "nanopb":
      In Podfile:
        FirebaseFirestore (from `https://github.com/invertase/firestore-ios-sdk-frameworks.git`, tag `11.0.0`) was resolved to 11.0.0, which depends on
          FirebaseFirestoreBinary (= 11.0.0) was resolved to 11.0.0, which depends on
            FirebaseFirestoreInternalBinary (= 11.0.0) was resolved to 11.0.0, which depends on
              nanopb (< 2.30911.0, >= 2.30908.0)

        firebase_crashlytics (from `.symlinks/plugins/firebase_crashlytics/ios`) was resolved to 4.0.4, which depends on
          Firebase/Crashlytics (= 11.0.0) was resolved to 11.0.0, which depends on
            FirebaseCrashlytics (~> 11.0.0) was resolved to 11.0.0, which depends on
              nanopb (~> 3.30910.0)
```

If I set Firestore to 11.0.0 in the Podfile, and 

```
    [!] CocoaPods could not find compatible versions for pod "FirebaseFirestore":
      In Podfile:
        FirebaseFirestore (from `https://github.com/invertase/firestore-ios-sdk-frameworks.git`, tag `10.29.0`)

        cloud_firestore (from `.symlinks/plugins/cloud_firestore/ios`) was resolved to 5.2.1, which depends on
          Firebase/Firestore (= 11.0.0) was resolved to 11.0.0, which depends on
            FirebaseFirestore (~> 11.0.0)
```

if I set it to 10.29.0

**Comment by Lyokone** [comment]
Thanks for the report, I'm having a look

**Comment by Lyokone** [comment]
Might take a bit more time than expected, a new version of the iOS SDK was released in parallel (11.1.0) which means we will need to update some other things. In the mean time you can remove this line from your Podfile
```
  pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => "11.0.0"
```
Sorry for the inconvenience, working on the fix

**Comment by Lyokone** [comment]
Fix has been pushed, Cocoapods might need a bit of time to surface it through its CDN. I'll keep this issue open for the time being.

**Comment by AndreyDAraya** [comment]
The fix, I talk with Google member and recommend this actions:

https://github.com/google/GoogleDataTransport/issues/149#issuecomment-2313898323

firebase_core: ^2.32.0
firebase_remote_config: ^4.4.7
firebase_analytics: ^10.10.7
...Other packages

Or the version old 3 month.

**Comment by jdbenito-atco** [comment]
Hmm, tis been a day since the deployment. I have re-enabled `pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '11.0.0'` and I'm getting the following error instead.

```
[!] CocoaPods could not find compatible versions for pod "FirebaseCoreExtension":
  In snapshot (Podfile.lock):
    FirebaseCoreExtension (= 11.1.0, ~> 11.0)

  In Podfile:
    FirebaseFirestore (from `https://github.com/invertase/firestore-ios-sdk-frameworks.git`, tag `11.0.0`) was resolved to 11.0.0, which depends on
      FirebaseFirestoreBinary (= 11.0.0) was resolved to 11.0.0, which depends on
        FirebaseCoreExtension (= 11.0.0)

Specs satisfying the `FirebaseCoreExtension (= 11.1.0, ~> 11.0), FirebaseCoreExtension (= 11.0.0)` dependency were found, but they required a higher minimum deployment target.
```

**Comment by darkLordOfTheCommit** [comment]
I am on `cloud_firestore ^5.3.0` and - after cleaning my Pods cache and deleting my pod lock file - I rtook a stab at removing the tag from the predownload link to get the latest:

```
target 'Runner' do
  use_frameworks!
  use_modular_headers!

  pod 'FirebaseFirestore',
  :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git'

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
```

After doing that, the predownload worked again and I was able to complete my Xcode build.  Back down to 38 seconds (from the pain of 6-7 mins since the breaking change).

>  If no version is specified on your current Firebase/Firestore pod then you can omit , :tag => '10.19.0' from the line above and use the latest version on master.

From https://github.com/invertase/firestore-ios-sdk-frameworks

**Comment by AlessandroMason** [comment]
Hi, 

still having the same issue, I didn't even have the pod file:

`[!] CocoaPods could not find compatible versions for pod "nanopb":
  In Podfile:
    cloud_firestore (from `.symlinks/plugins/cloud_firestore/ios`) was resolved to 5.3.0, which depends on
      Firebase/Firestore (= 11.0.0) was resolved to 11.0.0, which depends on
        FirebaseFirestore (~> 11.0.0) was resolved to 11.0.0, which depends on
          FirebaseFirestoreInternal (= 11.0.0) was resolved to 11.0.0, which depends on
            nanopb (~> 3.30910.0)

    mobile_scanner (from `.symlinks/plugins/mobile_scanner/ios`) was resolved to 5.2.1, which depends on
      GoogleMLKit/BarcodeScanning (~> 6.0.0) was resolved to 6.0.0, which depends on
        GoogleMLKit/MLKitCore (= 6.0.0) was resolved to 6.0.0, which depends on
          MLKitCommon (~> 11.0.0) was resolved to 11.0.0, which depends on
            GoogleDataTransport (< 10.0, >= 9.4.1) was resolved to 9.4.1, which depends on
              nanopb (< 2.30911.0, >= 2.30908.0)`
              
I don't have the suggested line in the PodFile to begin with and any combination of firebase dependencies version didn't help. How should I move forward?

**Comment by alisabry22** [comment]
same issue here while having the line of 
`pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '11.0.0'`

issue:
`CocoaPods could not find compatible versions for pod "nanopb":
  In Podfile:
    FirebaseFirestore (from `https://github.com/invertase/firestore-ios-sdk-frameworks.git`, tag `11.0.0`) was resolved to 11.0.0, which depends on
      FirebaseFirestoreBinary (= 11.0.0) was resolved to 11.0.0, which depends on
        FirebaseFirestoreInternalBinary (= 11.0.0) was resolved to 11.0.0, which depends on
          nanopb (< 2.30911.0, >= 2.30908.0)

    firebase_crashlytics (from `.symlinks/plugins/firebase_crashlytics/ios`) was resolved to 4.1.0, which depends on
      Firebase/Crashlytics (= 11.0.0) was resolved to 11.0.0, which depends on
        FirebaseCrashlytics (~> 11.0.0) was resolved to 11.0.0, which depends on
          nanopb (~> 3.30910.0)`

**Comment by kostasoft** [comment]
I added a constant to the Podfile and removed the 'FirebaseFirestore' versions of the pod
`$FirebaseSDKVersion = '10.29.0'
pod 'FirebaseFirestore' #, '~> 11.0.0'`

**Comment by Rheaparks** [comment]
> In my local environment, I was able to successfully install the Pods and start the app by executing the following commands:
> 
> ```
> rm -rf Pods
> rm -rf Podfile.lock
> pod repo remove trunk && pod setup
> pod install --repo-update
> ```

@ukkey0518 This solved the issue for me. Thanks for sharing.

**Comment by Lyokone** [comment]
Closing this issue since it should be solved for everyone and you have a way to reset your local pods using https://github.com/firebase/flutterfire/issues/13228#issuecomment-2325843150

Thanks all for your patience.

**Comment by oscarshaitan** [comment]
> In my local environment, I was able to successfully install the Pods and start the app by executing the following commands:
> 
> ```
> rm -rf Pods
> rm -rf Podfile.lock
> pod repo remove trunk && pod setup
> pod install --repo-update
> ```

not working for me sadly 

```
[!] CocoaPods could not find compatible versions for pod "GoogleDataTransport":
  In Podfile:
    firebase_performance (from `.symlinks/plugins/firebase_performance/ios`) was resolved to 0.10.0-5, which depends on
      Firebase/Performance (= 11.0.0) was resolved to 11.0.0, which depends on
        FirebasePerformance (~> 11.0.0) was resolved to 11.0.0, which depends on
          GoogleDataTransport (~> 10.0)

    mobile_scanner (from `.symlinks/plugins/mobile_scanner/ios`) was resolved to 5.2.2, which depends on
      GoogleMLKit/BarcodeScanning (~> 6.0.0) was resolved to 6.0.0, which depends on
        GoogleMLKit/MLKitCore (= 6.0.0) was resolved to 6.0.0, which depends on
          MLKitCommon (~> 11.0.0) was resolved to 11.0.0, which depends on
            GoogleDataTransport (< 10.0, >= 9.4.1)

```

**Comment by marciofrayze** [comment]
> > In my local environment, I was able to successfully install the Pods and start the app by executing the following commands:
> 
> > 
> 
> > ```
> 
> > rm -rf Pods
> 
> > rm -rf Podfile.lock
> 
> > pod repo remove trunk && pod setup
> 
> > pod install --repo-update
> 
> > ```
> 
> 
> 
> not working for me sadly 
> 
> 
> 
> ```
> 
> [!] CocoaPods could not find compatible versions for pod "GoogleDataTransport":
> 
>   In Podfile:
> 
>     firebase_performance (from `.symlinks/plugins/firebase_performance/ios`) was resolved to 0.10.0-5, which depends on
> 
>       Firebase/Performance (= 11.0.0) was resolved to 11.0.0, which depends on
> 
>         FirebasePerformance (~> 11.0.0) was resolved to 11.0.0, which depends on
> 
>           GoogleDataTransport (~> 10.0)
> 
> 
> 
>     mobile_scanner (from `.symlinks/plugins/mobile_scanner/ios`) was resolved to 5.2.2, which depends on
> 
>       GoogleMLKit/BarcodeScanning (~> 6.0.0) was resolved to 6.0.0, which depends on
> 
>         GoogleMLKit/MLKitCore (= 6.0.0) was resolved to 6.0.0, which depends on
> 
>           MLKitCommon (~> 11.0.0) was resolved to 11.0.0, which depends on
> 
>             GoogleDataTransport (< 10.0, >= 9.4.1)
> 
> 
> 
> ``` 

I don't think the problem you are experiencing is related to this bug report.

**Comment by mono0926** [comment]
@oscarshaitan 

> not working for me sadly

It's a similar issue, but it's different from this issue. 
It has been reported at https://github.com/juliansteenbakker/mobile_scanner/issues/1165, and we need Google to handle the upgrade to GoogleMLKit, but progress is slow.

**Comment by AlessandroMason** [comment]
Hi, actually worked when added this line to the Pod File (in the first line)


`$FirebaseSDKVersion = '10.29.0'`

**Comment by AlessandroMason** [comment]
> Hi,
> 
> still having the same issue, I don't have the line in the file but I have another dependency (mobile_scanner) that isn't supported anymore. Any suggestion on how to fix it?
> 
> ```
> [!] CocoaPods could not find compatible versions for pod "nanopb":
>   In Podfile:
>     cloud_firestore (from `.symlinks/plugins/cloud_firestore/ios`) was resolved to 5.3.0, which depends on
>       Firebase/Firestore (= 11.0.0) was resolved to 11.0.0, which depends on
>         FirebaseFirestore (~> 11.0.0) was resolved to 11.0.0, which depends on
>           FirebaseFirestoreInternal (= 11.0.0) was resolved to 11.0.0, which depends on
>             nanopb (~> 3.30910.0)
> 
> mobile_scanner (from `.symlinks/plugins/mobile_scanner/ios`) was resolved to 5.2.1, which depends on
>       GoogleMLKit/BarcodeScanning (~> 6.0.0) was resolved to 6.0.0, which depends on
>         GoogleMLKit/MLKitCore (= 6.0.0) was resolved to 6.0.0, which depends on
>           MLKitCommon (~> 11.0.0) was resolved to 11.0.0, which depends on
>             GoogleDataTransport (< 10.0, >= 9.4.1) was resolved to 9.4.1, which depends on
>               nanopb (< 2.30911.0, >= 2.30908.0)
> ```
Hi, actually worked when added this line to the Pod File (in the first line)

`$FirebaseSDKVersion = '10.29.0'`
