### ISSUE TITLE
🐛 [firebase_core] Platform channel not working

### ISSUE THREAD

**Issue by BugsOverBugs** [firebase/flutterfire#9012]
## Bug report

**Describe the bug**
With the lastet `firebase_core 1.19.0` the error `MissingPluginException(No implementation found for method Firebase#initializeCore on channel plugins.flutter.io/firebase_core)` is thrown.

### Steps to reproduce

I ran pub upgrade to the latest dependecies and after that firebase_core is not working on any platform. Before it works fine. I tested in two projects.

### Sample project

```
E/flutter (19610): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: MissingPluginException(No implementation found for method Firebase#initializeCore on channel plugins.flutter.io/firebase_core)
E/flutter (19610): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
E/flutter (19610): <asynchronous suspension>
E/flutter (19610): #1      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:353:35)
E/flutter (19610): <asynchronous suspension>
E/flutter (19610): #2      MethodChannelFirebase._initializeCore (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:31:23)
E/flutter (19610): <asynchronous suspension>
E/flutter (19610): #3      MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:73:7)
E/flutter (19610): <asynchronous suspension>
E/flutter (19610): #4      Firebase.initializeApp (package:firebase_core/src/firebase.dart:40:31)
E/flutter (19610): <asynchronous suspension>
```

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.3, on macOS 12.4 21F79 darwin-arm, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.68.1)
[✓] Connected device (5 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
- cloud_firestore_platform_interface 5.5.9 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.6.18 [cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_analytics_platform_interface 3.1.9 [firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.4.0+16 [firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_app_check_platform_interface 0.0.4+9 [firebase_core flutter meta plugin_platform_interface]
- firebase_app_check_web 0.0.5+15 [firebase_app_check_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_auth_platform_interface 6.3.0 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 3.3.18 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.4.1 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.6.5 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_dynamic_links_platform_interface 0.2.3+5 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 3.5.3 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 2.4.3 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- firebase_storage_platform_interface 4.1.9 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.2.18 [async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
```

</details>

---

**Comment by Zazo032** [comment]
I'm also getting an error on latest update:
```
Installing build/app/outputs/flutter-apk/app.apk...
E/flutter ( 7616): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: [core/no-app] No Firebase App '[DEFAULT]' has been created - call Firebase.initializeApp()
E/flutter ( 7616): #0      MethodChannelFirebase.app (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:173:5)
E/flutter ( 7616): #1      Firebase.app (package:firebase_core/src/firebase.dart:53:41)
E/flutter ( 7616): #2      FirebaseCrashlytics.instance (package:firebase_crashlytics/src/firebase_crashlytics.dart:33:55)
E/flutter ( 7616): #3      main.<anonymous closure> (package:craftos/main.dart:47:27)
E/flutter ( 7616): #4      _rootRunBinary (dart:async/zone.dart:1450:47)
E/flutter ( 7616): #5      _CustomZone.runBinary (dart:async/zone.dart:1342:19)
E/flutter ( 7616): #6      runZonedGuarded.<anonymous closure> (dart:async/zone.dart:1832:18)
E/flutter ( 7616): #7      _Zone._processUncaughtError (dart:async/zone.dart:1109:14)
E/flutter ( 7616): #8      _CustomZone.handleUncaughtError (dart:async/zone.dart:1312:5)
E/flutter ( 7616): #9      Future._propagateToListeners (dart:async/future_impl.dart:680:16)
E/flutter ( 7616): #10     Future._completeError (dart:async/future_impl.dart:574:5)
E/flutter ( 7616): #11     _completeOnAsyncError (dart:async-patch/async_patch.dart:287:13)
E/flutter ( 7616): #12     main.<anonymous closure> (package:craftos/main.dart)
E/flutter ( 7616): <asynchronous suspension>
```
It worked fine before updating to latest version, though

**Comment by Chetan-Goyal** [comment]
Old version is working. 

If anybody facing this issue, they can downgrade their firebase_core version to `1.17.1` using this syntax: 
`firebase_core: 1.17.1`. 

It should work atleast for now until the patch is released in the latest version.

**Comment by Zazo032** [comment]
Version `1.18.0` also works, the broken one is `1.19.0`

**Comment by alelav79** [comment]
Same problem with

1.18.0

:(

**Comment by alelav79** [comment]
> Version `1.18.0` also works, the broken one is `1.19.0`

Same problem with

1.18.0

:(

**Comment by BugsOverBugs** [comment]
> > Version `1.18.0` also works, the broken one is `1.19.0`
> 
> Same problem with
> 
> 1.18.0
> 
> :(

I do not, it works for me: `flutter clean`, than add `1.18.0` without `^` and `pub get`

**Comment by alelav79** [comment]
> > > Version `1.18.0` also works, the broken one is `1.19.0`
> > 
> > 
> > Same problem with
> > 1.18.0
> > :(
> 
> I do not, it works for me: `flutter clean`, than add `1.18.0` without `^` and `pub get`

Edited pubcpec.yaml

with

  firebase_core: 1.18.0

and in CLI

flutter clean
flutter packages get

Question : What does mean "^" before major ?

**Comment by saileshbro** [comment]
@alelav79 try doing `flutter pub cache clean` and `flutter packages get` with v `1.18.0` I fixed mine that way

**Comment by alelav79** [comment]
Thanks fo all !!!

**Comment by darshankawar** [comment]
@BugsOverBugs and everyone in this thread facing this issue.

The latest plugin's changelog says `Bump Firebase iOS SDK to 9.2.0` , so in your ios/podfile, if you have below entry and is pointing to `8.15.0` for example, can you try to update it to `9.2.0` and try again ?

`git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag =>`

**Comment by Zazo032** [comment]
@darshankawar our app doesn't support iOS, but it's still not working on Android

**Comment by saileshbro** [comment]
@darshankawar the issue is with Android as well.

**Comment by Lyokone** [comment]
Hi, this error is probably due to the migration of Firebase Core to use Pigeon (and thus new MethodChannels).
Has anyone of you tried to run `flutter clean` before running the app?

**Comment by Lyokone** [comment]
Could you send a copy of your pubspec.yaml?

**Comment by Zazo032** [comment]
```yaml
environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  aad_oauth:
    git:
      ref: flutter_web
      url: https://github.com/Zazo032/aad_oauth.git
  badges: ^2.0.3
  bloc_concurrency: ^0.2.0
  cached_network_image: ^3.2.1
  camerawesome: ^0.3.3
  carousel_slider: ^4.1.1
  custom_image_picker:
    git:
      url: https://github.com/Zazo032/custom_image_picker.git
  dio: ^4.0.6
  dio_firebase_performance:
    git:
      ref: patch-1
      url: https://github.com/Zazo032/dio_firebase_performance.git
  dio_smart_retry: ^1.2.0
  equatable: ^2.0.3
  feedback: ^2.5.0
  firebase_analytics: ^9.1.11
  firebase_core: 1.18.0
  firebase_crashlytics: ^2.8.3
  firebase_performance: ^0.8.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_html: ^3.0.0-alpha.5
  flutter_image_slideshow: ^0.1.2
  flutter_localizations:
    sdk: flutter
  flutter_signature_pad: ^3.0.1
  flutter_tabler_icons: ^1.1.1
  font_awesome_flutter: ^10.1.0
  gallery_saver: ^2.3.2
  google_fonts: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  jwt_decoder: ^2.0.1
  mobile_scanner: ^2.0.0
  open_file: ^3.2.1
  package_info_plus: ^1.4.2
  path_provider: ^2.0.11
  permission_handler: ^10.0.0
  photo_view: ^0.14.0
  slide_to_act: ^2.0.1
  upgrader: ^4.4.0
  url_launcher: ^6.1.4
  url_strategy: ^0.2.0

dependency_overrides:
  flutter_webview_plugin:
    git: https://github.com/Zazo032/flutter_webview_plugin

dev_dependencies:
  build_runner: ^2.1.11
  flutter_launcher_icons: ^0.9.3
  flutter_native_splash: ^2.2.3+1
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  very_good_analysis: ^3.0.1

flutter:
  generate: true
  uses-material-design: true
```

**Comment by Zazo032** [comment]
This is the initialization part of the app:

```dart
void main() {
  runZonedGuarded(
    () async {
      WidgetsFlutterBinding.ensureInitialized();
      await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform,
      );
      if (!kIsWeb) {
        FlutterError.onError = FirebaseCrashlytics.instance.recordFlutterError;
      }
      BlocOverrides.runZoned(
        () => runApp(const FlutterApp()),
        blocObserver: AppBlocObserver(),
      );
    },
    (error, stack) {
      FirebaseCrashlytics.instance.recordError(error, stack, fatal: true);
    },
  );
}
```

**Comment by Lyokone** [comment]
Could you try with 
```
  firebase_core: 1.19.0
```

and maybe If it doesn't work add this:
```
  firebase_core_platform_interface: 4.4.1
```

I thinks it's related to a transitive dependency not being updated

**Comment by Zazo032** [comment]
Same result after adding that platform interface to the pubspec. By checking the pubspec.yaml, seems like it's already using that version in 1.18

**Comment by Lyokone** [comment]
We have released version 1.19.1 of `firebase_core` that should solve the issue. Let us know if everything is good now :)

**Comment by Zazo032** [comment]
It seems to be working now. Thanks for the quick fix!

**Comment by Lyokone** [comment]
An unexpected issue with the release process, we'll try to keep an eye on that next time 👍

**Comment by dancamdev** [comment]
I'm still facing the issue with the following dependencies:

```yaml
cloud_firestore: ^3.2.1 
firebase_auth: ^3.4.1
firebase_core: ^1.19.1
```

**Comment by BugsOverBugs** [comment]
> I'm still facing the issue with the following dependencies:
> 
> ```yaml
> cloud_firestore: ^3.2.1 
> firebase_auth: ^3.4.1
> firebase_core: ^1.19.1
> ```

Run `flutter pub upgrade`. In my project they are working on all platforms again

**Comment by dancamdev** [comment]
> > I'm still facing the issue with the following dependencies:
> > ```yaml
> > cloud_firestore: ^3.2.1 
> > firebase_auth: ^3.4.1
> > firebase_core: ^1.19.1
> > ```
> 
> Run `flutter pub upgrade`. In my project they are working on all platforms again

nope, still not working when running on iOS, if there's other helpful info I can provide let me know!

**Comment by aytunch** [comment]
@dancamdev can you paste or SS the error logs you get?

**Comment by dancamdev** [comment]
Sure, here is the full log when running `flutter run` with iOS target

```
Launching lib/main.dart on iPhone 13 Pro in debug mode...
Running Xcode build...
Xcode build done.                                           13.3s
Failed to build iOS app
Error output from Xcode build:
↳
    2022-07-01 19:42:49.430 xcodebuild[91900:832035] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
    2022-07-01 19:42:49.431 xcodebuild[91900:832035] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
    ** BUILD FAILED **


Xcode's output:
↳
    Writing result bundle at path:
    	/var/folders/yv/415_mqjn13j0c7np7mskxf9r0000gn/T/flutter_tools.X8mNYy/flutter_ios_build_temp_dir4IqIr1/temporary_xcresult_bundle

    In file included from /Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/FLTSnapshotsInSyncStreamHandler.m:8:
    /Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/Private/FLTFirebaseFirestoreUtils.h:43:4: error: expected a type
    + (FIRFirestoreSource)FIRFirestoreSourceFromArguments:(NSDictionary *_Nonnull)arguments;
       ^
    /Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/Private/FLTFirebaseFirestoreUtils.h:45:4: error: expected a type
    + (FIRFirestore *_Nullable)getCachedFIRFirestoreInstanceForKey:(NSString *_Nonnull)key;
       ^
    /Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/Private/FLTFirebaseFirestoreUtils.h:46:40: error: expected a type
    + (void)setCachedFIRFirestoreInstance:(FIRFirestore *_Nonnull)firestore
                                           ^
    /Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/FLTSnapshotsInSyncStreamHandler.m:12:33: error: no type or protocol named 'FIRListenerRegistration'
    @property(readwrite, strong) id<FIRListenerRegistration> listenerRegistration;
                                    ^
    /Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/FLTSnapshotsInSyncStreamHandler.m:19:3: error: use of undeclared identifier 'FIRFirestore'
      FIRFirestore *firestore = arguments[@"firestore"];
      ^
    /Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/FLTSnapshotsInSyncStreamHandler.m:19:17: error: use of undeclared identifier 'firestore'
      FIRFirestore *firestore = arguments[@"firestore"];
                    ^
    /Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/FLTSnapshotsInSyncStreamHandler.m:27:32: error: use of undeclared identifier 'firestore'
      self.listenerRegistration = [firestore addSnapshotsInSyncListener:listener];
                                   ^
    /Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/FLTSnapshotsInSyncStreamHandler.m:33:30: error: no known instance method for selector 'remove'
      [self.listenerRegistration remove];
                                 ^~~~~~
    8 errors generated.
    In file included from /Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/FLTQuerySnapshotStreamHandler.m:8:
    /Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/Private/FLTFirebaseFirestoreUtils.h:43:4: error: expected a type
    + (FIRFirestoreSource)FIRFirestoreSourceFromArguments:(NSDictionary *_Nonnull)arguments;
       ^
    /Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/Private/FLTFirebaseFirestoreUtils.h:45:4: error: expected a type
    + (FIRFirestore *_Nullable)getCachedFIRFirestoreInstanceForKey:(NSString *_Nonnull)key;
       ^
    /Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/Private/FLTFirebaseFirestoreUtils.h:46:40: error: expected a type
    + (void)setCachedFIRFirestoreInstance:(FIRFirestore *_Nonnull)firestore
                                           ^
    /Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/FLTQuerySnapshotStreamHandler.m:12:33: error: no type or protocol named 'FIRListenerRegistration'
    @property(readwrite, strong) id<FIRListenerRegistration> listenerRegistration;
                                    ^
    /Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/FLTQuerySnapshotStreamHandler.m:19:3: error: use of undeclared identifier 'FIRQuery'
      FIRQuery *query = arguments[@"query"];
      ^
    /Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/FLTQuerySnapshotStreamHandler.m:19:13: error: use of undeclared identifier 'query'
      FIRQuery *query = arguments[@"query"];
                ^
    /Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/FLTQuerySnapshotStreamHandler.m:21:7: error: use of undeclared identifier 'query'
      if (query == nil) {
          ^
    /Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/FLTQuerySnapshotStreamHandler.m:31:19: error: type-id cannot have a name
      id listener = ^(FIRQuerySnapshot *_Nullable snapshot, NSError *_Nullable error) {
                      ^~~~~~~~~~~~~~~~
    /Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/FLTQuerySnapshotStreamHandler.m:31:36: error: expected ')'
      id listener = ^(FIRQuerySnapshot *_Nullable snapshot, NSError *_Nullable error) {
                                       ^
    /Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/FLTQuerySnapshotStreamHandler.m:31:18: note: to match this '('
      id listener = ^(FIRQuerySnapshot *_Nullable snapshot, NSError *_Nullable error) {
                     ^
    /Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/FLTQuerySnapshotStreamHandler.m:31:17: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
      id listener = ^(FIRQuerySnapshot *_Nullable snapshot, NSError *_Nullable error) {
                    ^
    /Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/FLTQuerySnapshotStreamHandler.m:32:9: error: use of undeclared identifier 'error'
        if (error) {
            ^
    /Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/FLTQuerySnapshotStreamHandler.m:33:91: error: use of undeclared identifier 'error'
          NSArray *codeAndMessage = [FLTFirebaseFirestoreUtils ErrorCodeAndMessageFromNSError:error];
                                                                                          ^
    /Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/FLTQuerySnapshotStreamHandler.m:44:62: error: use of undeclared identifier 'error'
                                              andOptionalNSError:error]);
                                                                 ^
    /Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/FLTQuerySnapshotStreamHandler.m:48:16: error: use of undeclared identifier 'snapshot'
            events(snapshot);
                   ^
    /Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/FLTQuerySnapshotStreamHandler.m:54:8: error: use of undeclared identifier 'query'
          [query addSnapshotListenerWithIncludeMetadataChanges:includeMetadataChanges.boolValue
           ^
    /Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/FLTQuerySnapshotStreamHandler.m:61:30: error: no known instance method for selector 'remove'
      [self.listenerRegistration remove];
                                 ^~~~~~
    1 warning and 15 errors generated.
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order

    Result bundle written to path:
    	/var/folders/yv/415_mqjn13j0c7np7mskxf9r0000gn/T/flutter_tools.X8mNYy/flutter_ios_build_temp_dir4IqIr1/temporary_xcresult_bundle


Parse Issue (Xcode): Expected a type
/Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/Private/FLTFirebaseFirestoreUtils.h:42:3

Parse Issue (Xcode): Expected a type
/Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/Private/FLTFirebaseFirestoreUtils.h:44:3

Parse Issue (Xcode): Expected a type
/Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/Private/FLTFirebaseFirestoreUtils.h:45:39

Generics Issue (Xcode): No type or protocol named 'FIRListenerRegistration'
/Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/FLTSnapshotsInSyncStreamHandler.m:11:32

Semantic Issue (Xcode): Use of undeclared identifier 'FIRFirestore'
/Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/FLTSnapshotsInSyncStreamHandler.m:18:2

Semantic Issue (Xcode): Use of undeclared identifier 'firestore'
/Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/FLTSnapshotsInSyncStreamHandler.m:18:16

Semantic Issue (Xcode): Use of undeclared identifier 'firestore'
/Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/FLTSnapshotsInSyncStreamHandler.m:26:31

ARC Semantic Issue (Xcode): No known instance method for selector 'remove'
/Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/FLTSnapshotsInSyncStreamHandler.m:32:29

Generics Issue (Xcode): No type or protocol named 'FIRListenerRegistration'
/Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/FLTQuerySnapshotStreamHandler.m:11:32

Semantic Issue (Xcode): Use of undeclared identifier 'FIRQuery'
/Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/FLTQuerySnapshotStreamHandler.m:18:2

Semantic Issue (Xcode): Use of undeclared identifier 'query'
/Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/FLTQuerySnapshotStreamHandler.m:18:12

Semantic Issue (Xcode): Use of undeclared identifier 'query'
/Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/FLTQuerySnapshotStreamHandler.m:20:6

Parse Issue (Xcode): Type-id cannot have a name
/Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/FLTQuerySnapshotStreamHandler.m:30:18

Parse Issue (Xcode): Expected ')'
/Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/FLTQuerySnapshotStreamHandler.m:30:35

Semantic Issue (Xcode): Use of undeclared identifier 'error'
/Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/FLTQuerySnapshotStreamHandler.m:31:8

Semantic Issue (Xcode): Use of undeclared identifier 'error'
/Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/FLTQuerySnapshotStreamHandler.m:32:90

Semantic Issue (Xcode): Use of undeclared identifier 'error'
/Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/FLTQuerySnapshotStreamHandler.m:43:61

Semantic Issue (Xcode): Use of undeclared identifier 'snapshot'
/Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/FLTQuerySnapshotStreamHandler.m:47:15

Semantic Issue (Xcode): Use of undeclared identifier 'query'
/Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/FLTQuerySnapshotStreamHandler.m:53:7

ARC Semantic Issue (Xcode): No known instance method for selector 'remove'
/Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/FLTQuerySnapshotStreamHandler.m:60:29

Parse Issue (Xcode): Expected a type
/Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/FLTFirebaseFirestoreWriter.m:82:39

Parse Issue (Xcode): Expected a type
/Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/FLTFirebaseFirestoreWriter.m:89:37

Parse Issue (Xcode): Expected a type
/Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/FLTFirebaseFirestoreWriter.m:135:39

Parse Issue (Xcode): Expected a type
/Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/FLTFirebaseFirestoreWriter.m:143:45

Parse Issue (Xcode): Expected a type
/Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/FLTFirebaseFirestoreWriter.m:166:36

Semantic Issue (Xcode): Use of undeclared identifier 'FIRTimestamp'
/Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/FLTFirebaseFirestoreWriter.m:18:35

Semantic Issue (Xcode): Unknown type name 'FIRTimestamp'; did you mean 'CVTimeStamp'?
/Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/FLTFirebaseFirestoreWriter.m:19:4

ARC Casting Rules (Xcode): Implicit conversion of Objective-C pointer type 'id' to C pointer type 'CVTimeStamp *' requires a bridged cast
/Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/FLTFirebaseFirestoreWriter.m:19:30

Semantic Issue (Xcode): Member reference type 'CVTimeStamp *' is a pointer; did you mean to use '->'?
/Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/FLTFirebaseFirestoreWriter.m:20:30

Semantic Issue (Xcode): No member named 'seconds' in 'CVTimeStamp'
/Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/FLTFirebaseFirestoreWriter.m:20:31

Semantic Issue (Xcode): Member reference type 'CVTimeStamp *' is a pointer; did you mean to use '->'?
/Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/FLTFirebaseFirestoreWriter.m:21:31

Semantic Issue (Xcode): No member named 'nanoseconds' in 'CVTimeStamp'
/Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/FLTFirebaseFirestoreWriter.m:21:32

Semantic Issue (Xcode): Use of undeclared identifier 'FIRGeoPoint'
/Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/FLTFirebaseFirestoreWriter.m:25:35

Semantic Issue (Xcode): Use of undeclared identifier 'FIRGeoPoint'
/Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/FLTFirebaseFirestoreWriter.m:26:4

Semantic Issue (Xcode): Use of undeclared identifier 'geoPoint'
/Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/FLTFirebaseFirestoreWriter.m:26:17

Semantic Issue (Xcode): Use of undeclared identifier 'geoPoint'
/Users/daniele/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.2.1/ios/Classes/FLTFirebaseFirestoreWriter.m:27:23

Error (Xcode): too many errors emitted, stopping now

Could not build the application for the simulator.
Error launching application on iPhone 13 Pro.
```

**Comment by dancamdev** [comment]
@darshankawar Sadly, it is not fixed, problem still persist even after trying all the solutions recommended in the other issue

**Comment by vixez** [comment]
I have users reporting crashing as well, after updating to `1.19.1` from a previous version on the store.
The store app immediately crashes. Reinstalling the app 'fixes' it.

**Comment by biplobsd** [comment]
> Version `1.18.0` also works, the broken one is `1.19.0`

This is change work for me.

```
firebase_core: 1.18.0
firebase_core_platform_interface: 4.4.1
```
