### ISSUE TITLE
🐛 [firebase_auth] signInWithPopup (web) fails on latest

### ISSUE THREAD

**Issue by cyberpwnn** [firebase/flutterfire#9124]
## Bug report

**Describe the bug**
There isnt really a useful error message but this just started failing on `3.4.2`

### Steps to reproduce

1. Invoke `FirebaseAuth.instance.signInWithPopup(GoogleAuthProvider())` as usual
2. See error

```
[Error]: [firebase_auth/argument-error] Error
[Error]: dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_
packages/firebase_auth_web/firebase_auth_web.dart 357:7                       signInWithPopup
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 60:31            <fn>
dart-sdk/lib/async/zone.dart 1690:54                                          runBinary
dart-sdk/lib/async/future_impl.dart 162:22                                    handleError
dart-sdk/lib/async/future_impl.dart 778:46                                    handleError
dart-sdk/lib/async/future_impl.dart 799:13                                    _propagateToListeners
dart-sdk/lib/async/future_impl.dart 574:5                                     [_completeError]
dart-sdk/lib/async/future_impl.dart 665:7                                     callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>
```

### Expected behavior

The popup should open as it did in `3.4.1`

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-arm, locale en-US)
    • Flutter version 3.0.5 at /Users/danielmills/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (3 days ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/danielmills/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Users/danielmills/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8609683/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Android Studio (version 2021.2)
    • Android Studio at /Users/danielmills/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8609683/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Android Studio (version 2021.2)
    • Android Studio at /Users/danielmills/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8512546/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.3)
    • IntelliJ at /Users/danielmills/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 69.0.4
    • Dart plugin version 221.5921.27

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.3)
    • IntelliJ at /Users/danielmills/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/221.5921.22/IntelliJ IDEA 2022.1 EAP.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.2)
    • IntelliJ at /Users/danielmills/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/221.5787.30/IntelliJ IDEA 2022.1 EAP.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.69.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • IN2017 (mobile) • 2e01d742 • android-arm64  • Android 11 (API 30)
    • macOS (desktop) • macos    • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)    • chrome   • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.17.6
Flutter SDK 3.0.5
myguide 1.0.4+4

dependencies:
- after_layout 1.2.0 [flutter]
- animated_text_kit 4.2.2 [flutter characters]
- archive 3.3.0 [crypto path]
- auto_size_text 3.0.0 [flutter]
- avatar_stack 1.1.2 [flutter]
- badges 2.0.3 [flutter]
- battery_plus 2.1.4 [flutter meta battery_plus_platform_interface battery_plus_linux battery_plus_macos battery_plus_web battery_plus_windows]
- blur 3.1.0 [flutter]
- blurhash_dart 1.1.0 [image]
- cached_network_image 3.2.1 [flutter flutter_cache_manager octo_image cached_network_image_platform_interface cached_network_image_web]
- carousel_slider 4.1.1 [flutter]
- chewie 1.3.4 [cupertino_icons flutter provider video_player wakelock]
- circle_list 1.0.5 [flutter]
- cloud_firestore 3.3.0 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cloud_functions 3.3.2 [cloud_functions_platform_interface cloud_functions_web firebase_core firebase_core_platform_interface flutter]
- colored_print 1.0.0
- confetti 0.7.0 [flutter vector_math]
- connectivity_plus 2.3.5 [flutter connectivity_plus_platform_interface connectivity_plus_linux connectivity_plus_macos connectivity_plus_web connectivity_plus_windows]
- cross_file 0.3.3+1 [js meta]
- crypto 3.0.2 [typed_data]
- cupertino_icons 1.0.5
- custom_navigation_bar 0.8.2 [flutter]
- date_time_format 2.0.1
- decorated_icon 1.2.1 [flutter]
- dots_indicator 2.1.0 [flutter]
- dough 1.0.3 [equatable flutter provider sensors vector_math]
- duration 3.0.11
- easy_localization 3.0.1 [flutter shared_preferences intl args path easy_logger flutter_localizations]
- easy_permission_validator 4.0.0 [flutter permission_handler]
- equatable 2.0.3 [collection meta]
- expandable_page_view 1.0.17 [flutter]
- file_picker 4.6.1 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface ffi path win32]
- filesize 2.0.1
- firebase_analytics 9.2.0 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 3.4.2 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.19.2 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 2.8.5 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_database 9.0.19 [firebase_core firebase_core_platform_interface firebase_database_platform_interface firebase_database_web flutter]
- firebase_messaging 12.0.0 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_performance 0.8.2 [firebase_core firebase_core_platform_interface firebase_performance_platform_interface firebase_performance_web flutter]
- firebase_remote_config 2.0.12 [firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface firebase_remote_config_web flutter]
- firebase_storage 10.3.2 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- fluid_kit 2.1.0 [flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_bounceable 1.0.3 [flutter]
- flutter_cache_manager 3.3.0 [clock collection file flutter http path path_provider pedantic rxdart sqflite uuid]
- flutter_cache_manager_firebase 2.0.1 [flutter flutter_cache_manager firebase_storage path_provider path]
- flutter_colorpicker 1.0.3 [flutter]
- flutter_dropzone 3.0.5 [flutter flutter_dropzone_platform_interface flutter_dropzone_web]
- flutter_fortune_wheel 1.2.0 [flutter flutter_hooks quiver]
- flutter_local_notifications 9.7.0 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_markdown 0.6.10+2 [flutter markdown meta path]
- flutter_native_splash 2.2.4 [args flutter flutter_web_plugins image js lint meta path universal_io xml yaml]
- flutter_picker 2.0.4 [flutter]
- flutter_scatter 0.2.0 [flutter]
- flutter_staggered_grid_view 0.6.2 [flutter]
- flutter_svg 1.1.1+1 [flutter meta path_drawing vector_math xml]
- fluttertoast 8.0.9 [flutter flutter_web_plugins]
- foil 0.9.0+1 [flutter sensors_plus]
- get 4.6.5 [flutter]
- glitcheffect 1.1.1 [flutter]
- google_fonts 3.0.1 [flutter http path_provider crypto]
- google_ml_kit 0.11.0 [flutter google_mlkit_barcode_scanning google_mlkit_digital_ink_recognition google_mlkit_face_detection google_mlkit_image_labeling google_mlkit_object_detection google_mlkit_pose_detection google_mlkit_selfie_segmentation google_mlkit_text_recognition google_mlkit_entity_extraction google_mlkit_language_id google_mlkit_translation google_mlkit_smart_reply]
- google_sign_in 5.4.0 [flutter google_sign_in_android google_sign_in_ios google_sign_in_platform_interface google_sign_in_web]
- googleapis 9.1.0 [_discoveryapis_commons http]
- gradient_ui_widgets 1.0.2-nullsafety [flutter]
- hand_signature 2.3.0+1 [flutter flutter_svg]
- hive 2.2.3 [meta crypto]
- hive_flutter 1.1.0 [flutter hive path_provider path]
- http 0.13.4 [async http_parser meta path]
- image 3.2.0 [archive meta xml]
- intl 0.17.0 [clock path]
- json_annotation 4.6.0 [meta]
- json_serializable 6.3.1 [analyzer async build build_config collection json_annotation meta path pub_semver pubspec_parse source_gen source_helper]
- just_audio 0.9.27 [just_audio_platform_interface just_audio_web audio_session rxdart path path_provider async uuid crypto meta flutter]
- just_waveform 0.0.3 [flutter path path_provider]
- lazy_loading_list 1.0.1 [flutter]
- local_auth 2.1.0 [flutter intl local_auth_android local_auth_ios local_auth_platform_interface local_auth_windows]
- lzstring 2.0.0+2 [typed_data]
- new_keyboard_shortcuts 0.1.4 [flutter visibility_detector tuple]
- oktoast 3.2.0 [flutter]
- package_info_plus 1.4.2 [flutter package_info_plus_platform_interface package_info_plus_linux package_info_plus_macos package_info_plus_windows package_info_plus_web]
- path_provider 2.0.11 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- patterns_canvas 0.4.0 [flutter]
- pdf 3.8.1 [archive barcode crypto image meta path_parsing vector_math xml]
- pinch_zoom 1.0.0 [flutter]
- preload_page_view 0.1.6 [flutter]
- provider 6.0.3 [collection flutter nested]
- quick_actions 0.6.0+11 [flutter quick_actions_android quick_actions_ios quick_actions_platform_interface]
- reactive_forms 13.0.0 [flutter intl]
- reflectable 3.0.9 [analyzer build build_resolvers build_config build_runner build_runner_core dart_style glob logging package_config path source_span]
- responsive_builder 0.4.2 [flutter]
- rxdart 0.27.5
- scratcher 2.2.1 [flutter]
- screenshot 1.2.3 [flutter]
- shared_preferences 2.0.15 [flutter shared_preferences_android shared_preferences_ios shared_preferences_linux shared_preferences_macos shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- shimmer 2.0.0 [flutter]
- sign_in_with_apple 4.0.0 [flutter meta sign_in_with_apple_platform_interface sign_in_with_apple_web]
- simple_gradient_text 1.2.3 [flutter]
- sliver_tools 0.2.7 [flutter]
- speech_balloon 0.0.4 [flutter]
- styled_text 5.1.0 [flutter xmlstream]
- syncfusion_flutter_calendar 20.2.38 [flutter timezone syncfusion_flutter_core syncfusion_flutter_datepicker intl]
- syncfusion_flutter_charts 20.2.38 [flutter intl vector_math syncfusion_flutter_core]
- syncfusion_flutter_datagrid 20.2.38 [flutter syncfusion_flutter_core collection]
- syncfusion_flutter_datepicker 20.2.38 [flutter intl syncfusion_flutter_core]
- syncfusion_flutter_gauges 20.2.38 [flutter syncfusion_flutter_core intl]
- syncfusion_flutter_sliders 20.2.38 [flutter intl syncfusion_flutter_core]
- syncfusion_flutter_treemap 20.2.38-beta [flutter syncfusion_flutter_core]
- syncfusion_localizations 20.2.38 [flutter intl syncfusion_flutter_core]
- synchronized 3.0.0+2
- tinycolor2 2.1.0 [flutter lint pigment]
- transparent_image 2.0.0
- universal_html 2.0.8 [async csslib charcode collection html meta source_span typed_data universal_io]
- universal_io 2.0.4 [collection crypto meta typed_data]
- url_launcher 6.1.5 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- uuid 3.0.6 [crypto]
- video_player 2.4.5 [flutter html video_player_android video_player_avfoundation video_player_platform_interface video_player_web]
- wakelock 0.6.2 [flutter meta wakelock_macos wakelock_platform_interface wakelock_web wakelock_windows]
- xl 0.9.1 [flutter sensors_plus]

dev dependencies:
- build_runner 2.2.0 [args async analyzer build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_gen_runner 4.3.0 [flutter_gen_core build collection crypto glob]
- flutter_launcher_icons 0.9.3 [args image path yaml]
- flutter_lints 2.0.1 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]

transitive dependencies:
- _discoveryapis_commons 1.0.3 [http http_parser meta]
- _fe_analyzer_shared 41.0.0 [meta]
- analyzer 4.2.0 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- args 2.3.1
- async 2.8.2 [collection meta]
- audio_session 0.1.9 [flutter flutter_web_plugins rxdart meta]
- barcode 2.2.1 [meta qr]
- battery_plus_linux 1.2.0 [flutter battery_plus_platform_interface meta upower]
- battery_plus_macos 1.1.1 [battery_plus_platform_interface flutter]
- battery_plus_platform_interface 1.2.1 [flutter meta plugin_platform_interface]
- battery_plus_web 1.1.0 [battery_plus_platform_interface flutter_web_plugins flutter]
- battery_plus_windows 1.1.2 [battery_plus_platform_interface flutter]
- boolean_selector 2.1.0 [source_span string_scanner]
- build 2.3.0 [analyzer async convert crypto glob logging meta path]
- build_config 1.1.0 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 3.1.0 [built_collection built_value http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.0.9 [analyzer async build crypto graphs logging path package_config pool pub_semver stream_transform yaml]
- build_runner_core 7.2.3 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.4.0 [built_collection collection fixnum meta]
- cached_network_image_platform_interface 1.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.0.1 [flutter flutter_cache_manager cached_network_image_platform_interface]
- characters 1.2.0
- charcode 1.3.1
- checked_yaml 2.0.1 [json_annotation source_span yaml]
- clock 1.1.0
- cloud_firestore_platform_interface 5.6.0 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.7.0 [cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- cloud_functions_platform_interface 5.1.11 [firebase_core flutter meta plugin_platform_interface]
- cloud_functions_web 4.3.0 [cloud_functions_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- code_builder 4.1.0 [built_collection built_value collection matcher meta]
- collection 1.16.0
- color 3.0.0
- connectivity_plus_linux 1.3.1 [flutter connectivity_plus_platform_interface meta nm]
- connectivity_plus_macos 1.2.4 [connectivity_plus_platform_interface flutter]
- connectivity_plus_platform_interface 1.2.1 [flutter meta plugin_platform_interface]
- connectivity_plus_web 1.2.2 [connectivity_plus_platform_interface flutter_web_plugins flutter]
- connectivity_plus_windows 1.2.2 [connectivity_plus_platform_interface flutter]
- convert 3.0.2 [typed_data]
- csslib 0.17.2 [source_span]
- dart_style 2.2.3 [analyzer args path pub_semver source_span]
- dartx 1.1.0 [characters collection crypto meta path time]
- dbus 0.7.4 [args ffi meta xml]
- easy_logger 0.0.2 [flutter]
- fake_async 1.3.0 [clock collection]
- ffi 1.2.1
- file 6.1.2 [meta path]
- firebase 9.0.3 [http http_parser js]
- firebase_analytics_platform_interface 3.2.0 [firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.4.1 [firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_auth_platform_interface 6.3.2 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 4.0.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.4.3 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 1.7.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.2.11 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_database_platform_interface 0.2.1+11 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_database_web 0.2.1 [firebase_core firebase_core_web firebase_database_platform_interface flutter flutter_web_plugins js]
- firebase_messaging_platform_interface 4.0.0 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.0.0 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- firebase_performance_platform_interface 0.1.1+11 [firebase_core flutter plugin_platform_interface]
- firebase_performance_web 0.1.1 [firebase firebase_core firebase_core_web firebase_performance_platform_interface flutter flutter_web_plugins js]
- firebase_remote_config_platform_interface 1.1.11 [firebase_core flutter meta plugin_platform_interface]
- firebase_remote_config_web 1.1.0 [firebase_core firebase_core_web firebase_remote_config_platform_interface flutter flutter_web_plugins js]
- firebase_storage_platform_interface 4.1.11 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.3.0 [async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- fixnum 1.0.1
- flutter_blurhash 0.7.0 [flutter]
- flutter_dropzone_platform_interface 2.0.5 [flutter plugin_platform_interface]
- flutter_dropzone_web 3.0.8 [flutter flutter_web_plugins flutter_dropzone_platform_interface js]
- flutter_gen_core 4.3.0 [path yaml mime xml dartx color collection json_annotation dart_style analyzer args pub_semver source_span]
- flutter_hooks 0.18.5+1 [flutter]
- flutter_local_notifications_linux 0.5.0+1 [flutter flutter_local_notifications_platform_interface dbus path xdg_directories]
- flutter_local_notifications_platform_interface 5.0.0 [flutter plugin_platform_interface]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_plugin_android_lifecycle 2.0.7 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- frontend_server_client 2.1.3 [async path]
- glob 2.1.0 [async collection file path string_scanner]
- google_mlkit_barcode_scanning 0.3.0 [flutter google_mlkit_commons]
- google_mlkit_commons 0.2.0 [flutter]
- google_mlkit_digital_ink_recognition 0.3.0 [flutter google_mlkit_commons]
- google_mlkit_entity_extraction 0.3.0 [flutter google_mlkit_commons]
- google_mlkit_face_detection 0.3.0 [flutter google_mlkit_commons]
- google_mlkit_image_labeling 0.3.0 [flutter google_mlkit_commons]
- google_mlkit_language_id 0.3.0 [flutter google_mlkit_commons]
- google_mlkit_object_detection 0.3.0 [flutter google_mlkit_commons]
- google_mlkit_pose_detection 0.3.0 [flutter google_mlkit_commons]
- google_mlkit_selfie_segmentation 0.0.1 [flutter google_mlkit_commons]
- google_mlkit_smart_reply 0.3.0 [flutter google_mlkit_commons]
- google_mlkit_text_recognition 0.3.0 [flutter google_mlkit_commons]
- google_mlkit_translation 0.3.0 [flutter google_mlkit_commons]
- google_sign_in_android 6.0.1 [flutter google_sign_in_platform_interface]
- google_sign_in_ios 5.4.0 [flutter google_sign_in_platform_interface]
- google_sign_in_platform_interface 2.2.0 [flutter quiver]
- google_sign_in_web 0.10.2 [flutter flutter_web_plugins google_sign_in_platform_interface js]
- graphs 2.1.0 [collection]
- html 0.15.0 [csslib source_span]
- http_multi_server 3.2.1 [async]
- http_parser 4.0.1 [collection source_span string_scanner typed_data]
- io 1.0.3 [meta path string_scanner]
- js 0.6.4
- just_audio_platform_interface 4.2.0 [flutter plugin_platform_interface]
- just_audio_web 0.4.7 [just_audio_platform_interface flutter flutter_web_plugins]
- lint 1.8.2
- lints 2.0.0
- local_auth_android 1.0.6 [flutter flutter_plugin_android_lifecycle intl local_auth_platform_interface]
- local_auth_ios 1.0.7 [flutter intl local_auth_platform_interface]
- local_auth_platform_interface 1.0.4 [flutter intl plugin_platform_interface]
- local_auth_windows 1.0.1 [flutter local_auth_platform_interface]
- logging 1.0.2
- markdown 5.0.0 [args charcode meta]
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.4
- meta 1.7.0
- mime 1.0.2
- nested 1.0.0 [flutter]
- nm 0.5.0 [dbus]
- octo_image 1.0.2 [flutter flutter_blurhash]
- package_config 2.1.0 [path]
- package_info_plus_linux 1.0.5 [package_info_plus_platform_interface flutter path]
- package_info_plus_macos 1.3.0 [flutter]
- package_info_plus_platform_interface 1.0.2 [flutter meta plugin_platform_interface]
- package_info_plus_web 1.0.5 [flutter flutter_web_plugins http meta package_info_plus_platform_interface]
- package_info_plus_windows 1.0.5 [package_info_plus_platform_interface ffi flutter win32]
- path 1.8.1
- path_drawing 1.0.0 [vector_math meta path_parsing flutter]
- path_parsing 1.0.0 [vector_math meta]
- path_provider_android 2.0.16 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.10 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.7 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.6 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.4 [flutter platform plugin_platform_interface]
- path_provider_windows 2.0.7 [ffi flutter path path_provider_platform_interface win32]
- pedantic 1.11.1
- permission_handler 9.2.0 [flutter meta permission_handler_android permission_handler_apple permission_handler_windows permission_handler_platform_interface]
- permission_handler_android 9.0.2+1 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.0.4 [flutter permission_handler_platform_interface]
- permission_handler_platform_interface 3.7.0 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.1.0 [flutter permission_handler_platform_interface]
- petitparser 5.0.0 [meta]
- pigment 1.0.4 [flutter]
- platform 3.1.0
- plugin_platform_interface 2.1.2 [meta]
- pool 1.5.1 [async stack_trace]
- process 4.2.4 [file path platform]
- pub_semver 2.1.1 [collection meta]
- pubspec_parse 1.2.0 [checked_yaml collection json_annotation pub_semver yaml]
- qr 3.0.1 [meta]
- quick_actions_android 0.6.1 [flutter quick_actions_platform_interface]
- quick_actions_ios 0.6.0+11 [flutter quick_actions_platform_interface]
- quick_actions_platform_interface 1.0.2 [flutter plugin_platform_interface]
- quiver 3.1.0 [matcher]
- sensors 2.0.3 [flutter]
- sensors_plus 1.3.2 [flutter sensors_plus_web sensors_plus_platform_interface]
- sensors_plus_platform_interface 1.1.1 [flutter meta plugin_platform_interface]
- sensors_plus_web 1.1.1 [flutter sensors_plus_platform_interface flutter_web_plugins]
- shared_preferences_android 2.0.12 [flutter shared_preferences_platform_interface]
- shared_preferences_ios 2.1.1 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.1.1 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_macos 2.0.4 [flutter shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.4 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.1.1 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.3.1 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 1.0.2 [shelf stream_channel web_socket_channel]
- sign_in_with_apple_platform_interface 1.0.0 [flutter plugin_platform_interface meta]
- sign_in_with_apple_web 1.0.1 [flutter flutter_web_plugins sign_in_with_apple_platform_interface js]
- sky_engine 0.0.99
- source_gen 1.2.2 [analyzer async build dart_style glob meta path source_span yaml]
- source_helper 1.3.2 [analyzer collection source_gen]
- source_span 1.8.2 [collection path term_glyph]
- sqflite 2.0.3 [flutter sqflite_common path]
- sqflite_common 2.2.1+1 [synchronized path meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- syncfusion_flutter_core 20.2.38 [vector_math flutter]
- term_glyph 1.2.0
- test_api 0.4.9 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- time 2.1.1 [clock]
- timezone 0.8.0 [path]
- timing 1.0.0 [json_annotation]
- tuple 2.0.0 [quiver]
- typed_data 1.3.1 [collection]
- upower 0.7.0 [dbus]
- url_launcher_android 6.0.17 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.0.17 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.1.0 [flutter plugin_platform_interface]
- url_launcher_web 2.0.12 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.1 [flutter url_launcher_platform_interface]
- vector_math 2.1.2
- video_player_android 2.3.7 [flutter video_player_platform_interface]
- video_player_avfoundation 2.3.5 [flutter video_player_platform_interface]
- video_player_platform_interface 5.1.3 [flutter plugin_platform_interface]
- video_player_web 2.0.10 [flutter flutter_web_plugins video_player_platform_interface]
- visibility_detector 0.2.2 [flutter]
- wakelock_macos 0.4.0 [flutter flutter_web_plugins wakelock_platform_interface]
- wakelock_platform_interface 0.3.0 [flutter meta]
- wakelock_web 0.4.0 [flutter flutter_web_plugins js wakelock_platform_interface]
- wakelock_windows 0.2.0 [flutter wakelock_platform_interface win32]
- watcher 1.0.1 [async path]
- web_socket_channel 2.2.0 [async crypto stream_channel]
- win32 2.6.1 [ffi]
- xdg_directories 0.2.0+1 [meta path process]
- xml 6.1.0 [collection meta petitparser]
- xmlstream 1.0.0
- yaml 3.1.1 [collection source_span string_scanner]

```

</details>

---

**Comment by Faizan770gp** [comment]
Latest FirebaseAuth 3.4.2 WEB authStateChanges also not persisting user anymore. It goes back to the login screen as soon as i reload the app works perfectly fine on **firebase_auth: 3.3.20**

**Comment by iBehruz** [comment]
same bug ++

**Comment by bw-flagship** [comment]
Same here! I figured out that it happens when upgrading firebase_core_web indirectly.

```
  firebase_auth: any
  firebase_core: any

  # works:
  firebase_core_web: 1.6.6

  # broken:
  # firebase_core_web: 1.7.0
```

**Comment by duckroll** [comment]
How do you change the version of firebase_core_web?

**Comment by duckroll** [comment]
If you are wondering how to change firebase_core_web version:

```
  firebase_auth: ^3.4.1
  firebase_core: ^1.19.1
```

I changed went down on both auth and core versions by 1 and it works now

**Comment by asm495** [comment]
Same issue for me. To get the web login working again I had to do a downgrade on a whole bunch of packages as shown below. The comments are the version numbers I was trying to use previously.

```
  firebase_database: ^9.0.17 # was 9.0.19 (web fix)
  flutterfire_ui: ^0.4.2 # was 4.2+3 (web fix)
  cloud_firestore: ^3.2.1 # was 3.3.0 (web fix)
  firebase_messaging: ^11.4.4 # was 12.0.0 (web fix)
  firebase_storage: ^10.2.18 # was 10.3.2 (web fix)
  cloud_functions: ^3.2.17 # was 3.3.2 (web fix)
  firebase_analytics: ^9.1.12 # was 9.2.0 (web fix)
```

It has allowed me to login to the web again and seems to work on Android/iOS too.

**Comment by bw-flagship** [comment]
Instead of downgrading several packages manually, you can just add

`firebase_core_web: 1.6.6`

to your pubspec.yaml

**Comment by asm495** [comment]
> Instead of downgrading several packages manually, you can just add
> 
> `firebase_core_web: 1.6.6`
> 
> to your pubspec.yaml

Unfortunately that didn't work for me. Too many cross-dependencies and I couldn't get a working build.

**Comment by monkeydaichan** [comment]
I have same issue.

**Comment by aalokdosii** [comment]
Facing same issue.

**Comment by stenlee** [comment]
same issue here 
And now with the current release of firebase_auth 3.5.0 - NO combination of dependencies is working anymore
My app is dead and users can't log in :/

**Comment by stenlee** [comment]
I gave a last try to play with dependencies and finally found something that works ... hope it helps someone
```
firebase_core_web: 1.6.6
firebase_auth: 3.4.1
firebase_analytics: 9.1.12
firebase_core: 1.19.1
firebase_performance: 0.8.1+1
firebase_storage: 10.3.1
cloud_firestore: 3.2.1
cloud_firestore_platform_interface: 5.5.10
firebase_analytics_platform_interface: 3.1.10
firebase_auth_platform_interface: 6.3.1
```

**Comment by thepelican** [comment]
yep firebase_auth 3.5.0 did not fix this issue

**Comment by PranayDosii** [comment]
Then why did you close this issue?

**Comment by petodavid** [comment]
Its not fixed, do not close it

**Comment by HoaLebao** [comment]
I have this issue after upgraded to the latest.

    • Flutter version 3.0.5 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (9 days ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

  firebase_auth 3.5.0
  firebase_auth_platform_interface 6.4.0
  firebase_auth_web 4.1.0
  firebase_core 1.20.0
  firebase_core_platform_interface 4.5.0
  firebase_core_web 1.7.1

**Comment by aalokdosii** [comment]
This issue still exists. Please reopen it.

**Comment by bw-flagship** [comment]
I can confirm that this is not fixed. In addition, the so-called fix did not contain any kind of test changes; therefore I suppose even if this will be fixed it can happen again any time.

**Comment by vilorel** [comment]
Broken for me too, yet another confirmation to this thread. It's a bit disappointing to see package updates breaking basic flows like this one. I

**Comment by PranayDosii** [comment]
This issue is not fixed and without any testing they closed this issue

**Comment by wouternivelle** [comment]
It seems it's fixed in #9146 2 days ago, but the most recent release was 0.4.3 which was 3 days ago.

**Comment by vilorel** [comment]
FYI, everyone, they released a new firebase_auth version and now it works for me.

**Comment by csukmacodes** [comment]
> FYI, everyone, they released a new firebase_auth version and now it works for me.

version 3.5.1 fixed this bug

**Comment by bw-flagship** [comment]
For me its not fixed, it just became another error. Not it says

`TypeError: Cannot read properties of undefined (reading 'auth')`
