### ISSUE TITLE
🐛 [firebase_auth] firebase_auth 4.1.0 should depend on firebase_auth_platform_interface 6.11.0

### ISSUE THREAD

**Issue by davidmigloz** [firebase/flutterfire#9803]
## Bug report

The new version of firebase_auth (4.1.0) [depends on](https://github.com/firebase/flutterfire/blob/firebase_auth-v4.1.0/packages/firebase_auth/firebase_auth/pubspec.yaml) `firebase_auth_platform_interface: ^6.10.4` which does not contain the new `verify` method.

It should depend on `firebase_auth_platform_interface: ^6.11.0` instead.

Error logs:
<details><summary>Click To Expand</summary>

```
../../../../.pub-cache/hosted/pub.dartlang.org/firebase_auth-4.1.0/lib/src/c
onfirmation_result.dart:17:32: Error: Member not found:
'ConfirmationResultPlatform.verify'.
    ConfirmationResultPlatform.verify(_delegate);
                               ^^^^^^
../../../../.pub-cache/hosted/pub.dartlang.org/firebase_auth-4.1.0/lib/src/m
ulti_factor.dart:67:34: Error: Member not found:
'MultiFactorAssertionPlatform.verify'.
    MultiFactorAssertionPlatform.verify(_delegate);
                                 ^^^^^^
../../../../.pub-cache/hosted/pub.dartlang.org/firebase_auth-4.1.0/lib/src/m
ulti_factor.dart:78:33: Error: Member not found:
'MultiFactorResolverPlatform.verify'.
    MultiFactorResolverPlatform.verify(_delegate);
                                ^^^^^^
../../../../.pub-cache/hosted/pub.dartlang.org/firebase_auth-4.1.0/lib/src/u
ser.dart:16:18: Error: Member not found: 'UserPlatform.verify'.
    UserPlatform.verify(_delegate);
                 ^^^^^^
../../../../.pub-cache/hosted/pub.dartlang.org/firebase_auth-4.1.0/lib/src/u
ser.dart:364:21: Error: The method 'reauthenticateWithRedirect' isn't
defined for the class 'UserPlatform'.
 - 'UserPlatform' is from
 'package:firebase_auth_platform_interface/src/platform_interface/platform_i
 nterface_user.dart'
 ('../../../../.pub-cache/hosted/pub.dartlang.org/firebase_auth_platform_int
 erface-6.10.4/lib/src/platform_interface/platform_interface_user.dart').
Try correcting the name to the name of an existing method, or defining a
method named 'reauthenticateWithRedirect'.
    await _delegate.reauthenticateWithRedirect(provider);
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
../../../../.pub-cache/hosted/pub.dartlang.org/firebase_auth-4.1.0/lib/src/u
ser_credential.dart:12:28: Error: Member not found:
'UserCredentialPlatform.verify'.
    UserCredentialPlatform.verify(_delegate);
```

</details>

### Steps to reproduce

1. Try to compile using firebase_auth 4.1.0

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by danagbemava-nc** [comment]
Hi @davidmigloz, can you try clearing your pub cache and trying again? I added `firebase_core` and `firebase_auth` to a new project and `firebase_auth_platform_interface` was resolved to 6.11.0 for me so I had no issue running the app. 

See below for the results of running `flutter pub add firebase_core && flutter pub add firebase_auth`

```
flutter pub add firebase_core && flutter pub add firebase_auth   
Resolving dependencies...
  async 2.9.0 (2.10.0 available)
  boolean_selector 2.1.0 (2.1.1 available)
  collection 1.16.0 (1.17.0 available)
+ firebase_core 2.1.1
+ firebase_core_platform_interface 4.5.2
+ firebase_core_web 2.0.1
+ flutter_web_plugins 0.0.0 from sdk flutter
+ js 0.6.4 (0.6.5 available)
  matcher 0.12.12 (0.12.13 available)
  material_color_utilities 0.1.5 (0.2.0 available)
+ plugin_platform_interface 2.1.3
  source_span 1.9.0 (1.9.1 available)
  stack_trace 1.10.0 (1.11.0 available)
  stream_channel 2.1.0 (2.1.1 available)
  test_api 0.4.12 (0.4.15 available)
  vector_math 2.1.2 (2.1.4 available)
Downloading firebase_core 2.1.1...
Downloading firebase_core_web 2.0.1...
Downloading firebase_core_platform_interface 4.5.2...
Changed 6 dependencies!
Resolving dependencies...
+ _flutterfire_internals 1.0.6
  async 2.9.0 (2.10.0 available)
  boolean_selector 2.1.0 (2.1.1 available)
+ cloud_firestore_platform_interface 5.8.3
+ cloud_firestore_web 3.0.3
  collection 1.16.0 (1.17.0 available)
+ firebase_auth 4.1.0
+ firebase_auth_platform_interface 6.11.0
+ firebase_auth_web 5.1.0
+ http_parser 4.0.2
+ intl 0.17.0
  js 0.6.4 (0.6.5 available)
  matcher 0.12.12 (0.12.13 available)
  material_color_utilities 0.1.5 (0.2.0 available)
  source_span 1.9.0 (1.9.1 available)
  stack_trace 1.10.0 (1.11.0 available)
  stream_channel 2.1.0 (2.1.1 available)
  test_api 0.4.12 (0.4.15 available)
+ typed_data 1.3.1
  vector_math 2.1.2 (2.1.4 available)
Downloading firebase_auth 4.1.0...
Downloading firebase_auth_web 5.1.0...
Downloading firebase_auth_platform_interface 6.11.0...
Downloading _flutterfire_internals 1.0.6...
Downloading cloud_firestore_web 3.0.3...
Downloading cloud_firestore_platform_interface 5.8.3...
Changed 9 dependencies!
```

**Comment by davidmigloz** [comment]
It was a cache issue indeed, as the caret syntax (`^6.10.4`) resolves up to the minor version (I thought it was only up to the path). After clearing the pub cache it's being resolved to 6.11.0.

Anyway, the constraints declared in the [`firebase_auth` pubspec](https://github.com/firebase/flutterfire/blob/firebase_auth-v4.1.0/packages/firebase_auth/firebase_auth/pubspec.yaml) are still wrong, as you cannot compile the current code with `firebase_auth_platform_interface 6.10.4`. So it should be bumped to `firebase_auth_platform_interface: ^6.11.0`.

**Comment by danagbemava-nc** [comment]
Thanks for the info. Labeling for further insight from the team.

**Comment by Purus** [comment]
These kind of issues are occurring more common recently, IIRC.  I believe it's hard to maintain the dependent library  version correctly.

**Comment by davidmigloz** [comment]
Is the caret syntax adding any value for internal first-party dependencies? If exact versions had been used instead, this bug wouldn't have been hidden while resolving dependencies.

**Comment by romarito** [comment]
> Thanks for the info. Labeling for further insight from the team.

Label "urgency" please, I missed half a Saturday to get here and then provisionally go back to version 4.0.1.

**Comment by ps6067966** [comment]
firebase_auth: 4.1.0 is not working. please check.

**Comment by davidmigloz** [comment]
You can delete your `pubspec.lock` and trigger a `flutter pub get` again. It should resolve `firebase_auth_platform_interface: 6.11.0`.

If it still resolves `firebase_auth_platform_interface: 6.10.4`, you can override it:
```
dependency_overrides:
  firebase_auth_platform_interface: 6.11.0
```

**Comment by russellwheatley** [comment]
Thanks for the report, @davidmigloz. We'll be releasing tomorrow so I'll ensure the version is bumped. We use melos to handle versioning across all the plugins so I'm surprised it hasn't bumped the `firebase_auth_platform_interface` dependency.

**Comment by Lyokone** [comment]
Hello, we have just released a new version that depends on the right `firebase_auth_platform_interface`, thanks for the report, we are investigating why melos hasn't properly bumped it.
